var COMPILED=!0,goog=goog||{};goog.global=this;goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]?c[d]:c[d]={}:c[d]=b};goog.define=function(a,b){var c=b;COMPILED||goog.global.CLOSURE_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_DEFINES,a)&&(c=goog.global.CLOSURE_DEFINES[a]);goog.exportPath_(a,c)};goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;
goog.provide=function(a){if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a];for(var b=a;(b=b.substring(0,b.lastIndexOf(".")))&&!goog.getObjectByName(b);)goog.implicitNamespaces_[b]=!0}goog.exportPath_(a)};goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};
COMPILED||(goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)},goog.implicitNamespaces_={});goog.getObjectByName=function(a,b){for(var c=a.split("."),d=b||goog.global,e;e=c.shift();)if(goog.isDefAndNotNull(d[e]))d=d[e];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};
goog.addDependency=function(a,b,c){if(goog.DEPENDENCIES_ENABLED){var d;a=a.replace(/\\/g,"/");for(var e=goog.dependencies_,f=0;d=b[f];f++)e.nameToPath[d]=a,a in e.pathToNames||(e.pathToNames[a]={}),e.pathToNames[a][d]=!0;for(d=0;b=c[d];d++)a in e.requires||(e.requires[a]={}),e.requires[a][b]=!0}};goog.ENABLE_DEBUG_LOADER=!0;
goog.require=function(a){if(!COMPILED&&!goog.isProvided_(a)){if(goog.ENABLE_DEBUG_LOADER){var b=goog.getPathFromDeps_(a);if(b){goog.included_[b]=!0;goog.writeScripts_();return}}a="goog.require could not find: "+a;goog.global.console&&goog.global.console.error(a);throw Error(a);}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a,b){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};
goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];goog.DEPENDENCIES_ENABLED=!COMPILED&&goog.ENABLE_DEBUG_LOADER;
goog.DEPENDENCIES_ENABLED&&(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var c=a[b].src,d=c.lastIndexOf("?"),d=-1==d?c.length:
d;if("base.js"==c.substr(d-7,7)){goog.basePath=c.substr(0,d-7);break}}},goog.importScript_=function(a){var b=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;!goog.dependencies_.written[a]&&b(a)&&(goog.dependencies_.written[a]=!0)},goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()){var b=goog.global.document;if("complete"==b.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}b.write('<script type="text/javascript" src="'+a+'">\x3c/script>');
return!0}return!1},goog.writeScripts_=function(){function a(e){if(!(e in d.written)){if(!(e in d.visited)&&(d.visited[e]=!0,e in d.requires))for(var g in d.requires[e])if(!goog.isProvided_(g))if(g in d.nameToPath)a(d.nameToPath[g]);else throw Error("Undefined nameToPath for "+g);e in c||(c[e]=!0,b.push(e))}}var b=[],c={},d=goog.dependencies_,e;for(e in goog.included_)d.written[e]||a(e);for(e=0;e<b.length;e++)if(b[e])goog.importScript_(goog.basePath+b[e]);else throw Error("Undefined script input");
},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};
goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=!1;c.appendChild(b.createTextNode(a));b.body.appendChild(c);
b.body.removeChild(c)}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,b){var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split("-");for(var b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join("-")},d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?c:d:function(a){return a};return b?a+"-"+d(b):d(a)};goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){var c=b||{},d;for(d in c){var e=(""+c[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),e)}return a};goog.getMsgWithFallback=function(a,b){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};
goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a};
goog.base=function(a,b,c){var d=arguments.callee.caller;if(goog.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() expects not to be running in strict mode. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var e=Array.prototype.slice.call(arguments,2),f=!1,g=a.constructor;g;g=g.superClass_&&g.superClass_.constructor)if(g.prototype[b]===d)f=!0;else if(f)return g.prototype[b].apply(a,
e);if(a[b]===d)return a.constructor.prototype[b].apply(a,e);throw Error("goog.base called from a method of one name to a method of a different name");};goog.scope=function(a){a.call(goog.global)};/*
 Dual licensed under the MIT or GPL licenses.
*/
var pike={animation:{}};pike.animation.Animator=function(a){this.duration_=a;this.repeatCount_=pike.animation.Animator.INFINITE;this.loopsDone_=0;this.repeatBehavior_=pike.animation.Animator.RepeatBehavior.REVERSE;this.timeSinceLoopStart_=0;this.reverseLoop_=this.running_=this.started_=!1};pike.animation.Animator.INFINITE=-1;pike.animation.Animator.RepeatBehavior={LOOP:1,REVERSE:2};pike.animation.Animator.prototype.start=function(){this.running_=this.started_=!0};
pike.animation.Animator.prototype.isRunning=function(){return this.running_};pike.animation.Animator.prototype.stop=function(){this.timeSinceLoopStart_=this.loopsDone_=0;this.started_=this.running_=!1};pike.animation.Animator.prototype.pause=function(){this.running_=!1};
pike.animation.Animator.prototype.update=function(a){if(this.started_){this.running_||(a=0);this.timeSinceLoopStart_+=a;if(this.timeSinceLoopStart_>=this.duration_&&(a=Math.floor(this.timeSinceLoopStart_/this.duration_),this.timeSinceLoopStart_%=this.duration_,this.repeatCount_!=pike.animation.Animator.INFINITE&&a>this.repeatCount_-this.loopsDone_&&(a=this.repeatCount_-this.loopsDone_),this.loopsDone_+=a,this.reverseLoop_=this.repeatBehavior_==pike.animation.Animator.RepeatBehavior.REVERSE&&1==this.loopsDone_%
2,this.repeatCount_!=pike.animation.Animator.INFINITE&&this.loopsDone_==this.repeatCount_)){this.stop();return}a=this.timeSinceLoopStart_/this.duration_;this.reverseLoop_&&(a=0.99999999999999-a);return a}};pike.animation.Animator.prototype.throwIfStarted_=function(){if(this.started_)throw Error("Cannot change property on the started animator");};pike.animation.Animator.prototype.getDuration=function(){return this.duration_};
pike.animation.Animator.prototype.setDuration=function(a){this.throwIfStarted_();if(1>a)throw Error("Duration can't be < 1");this.duration_=a};pike.animation.Animator.prototype.setRepeatCount=function(a){this.throwIfStarted_();if(1>a&&a!=pike.animation.Animator.INFINITE)throw Error("Repeat count must be greater than 0 or INFINITE");this.repeatCount_=a};pike.animation.Animator.prototype.getRepeatCount=function(){return this.repeatCount_};
pike.animation.Animator.prototype.setRepeatBehavior=function(a){return this.repeatBehavior_=a};pike.animation.Animator.prototype.getRepeatBehavior=function(){return this.repeatBehavior_};goog.disposable={};goog.disposable.IDisposable=function(){};goog.Disposable=function(){goog.Disposable.MONITORING_MODE!=goog.Disposable.MonitoringMode.OFF&&(this.creationStack=Error().stack,goog.Disposable.instances_[goog.getUid(this)]=this)};goog.Disposable.MonitoringMode={OFF:0,PERMANENT:1,INTERACTIVE:2};goog.Disposable.MONITORING_MODE=0;goog.Disposable.instances_={};goog.Disposable.getUndisposedObjects=function(){var a=[],b;for(b in goog.Disposable.instances_)goog.Disposable.instances_.hasOwnProperty(b)&&a.push(goog.Disposable.instances_[Number(b)]);return a};
goog.Disposable.clearUndisposedObjects=function(){goog.Disposable.instances_={}};goog.Disposable.prototype.disposed_=!1;goog.Disposable.prototype.isDisposed=function(){return this.disposed_};goog.Disposable.prototype.getDisposed=goog.Disposable.prototype.isDisposed;
goog.Disposable.prototype.dispose=function(){if(!this.disposed_&&(this.disposed_=!0,this.disposeInternal(),goog.Disposable.MONITORING_MODE!=goog.Disposable.MonitoringMode.OFF)){var a=goog.getUid(this);if(goog.Disposable.MONITORING_MODE==goog.Disposable.MonitoringMode.PERMANENT&&!goog.Disposable.instances_.hasOwnProperty(a))throw Error(this+" did not call the goog.Disposable base constructor or was disposed of after a clearUndisposedObjects call");delete goog.Disposable.instances_[a]}};
goog.Disposable.prototype.registerDisposable=function(a){this.addOnDisposeCallback(goog.partial(goog.dispose,a))};goog.Disposable.prototype.addOnDisposeCallback=function(a,b){this.onDisposeCallbacks_||(this.onDisposeCallbacks_=[]);this.onDisposeCallbacks_.push(goog.bind(a,b))};goog.Disposable.prototype.disposeInternal=function(){if(this.onDisposeCallbacks_)for(;this.onDisposeCallbacks_.length;)this.onDisposeCallbacks_.shift()()};
goog.Disposable.isDisposed=function(a){return a&&"function"==typeof a.isDisposed?a.isDisposed():!1};goog.dispose=function(a){a&&"function"==typeof a.dispose&&a.dispose()};goog.disposeAll=function(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];goog.isArrayLike(d)?goog.disposeAll.apply(null,d):goog.dispose(d)}};goog.events={};goog.events.Event=function(a,b){this.type=a;this.currentTarget=this.target=b};goog.events.Event.prototype.disposeInternal=function(){};goog.events.Event.prototype.dispose=function(){};goog.events.Event.prototype.propagationStopped_=!1;goog.events.Event.prototype.defaultPrevented=!1;goog.events.Event.prototype.returnValue_=!0;goog.events.Event.prototype.stopPropagation=function(){this.propagationStopped_=!0};
goog.events.Event.prototype.preventDefault=function(){this.defaultPrevented=!0;this.returnValue_=!1};goog.events.Event.stopPropagation=function(a){a.stopPropagation()};goog.events.Event.preventDefault=function(a){a.preventDefault()};goog.debug={};goog.debug.Error=function(a){Error.captureStackTrace?Error.captureStackTrace(this,goog.debug.Error):this.stack=Error().stack||"";a&&(this.message=String(a))};goog.inherits(goog.debug.Error,Error);goog.debug.Error.prototype.name="CustomError";goog.string={};goog.string.Unicode={NBSP:"\u00a0"};goog.string.startsWith=function(a,b){return 0==a.lastIndexOf(b,0)};goog.string.endsWith=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};goog.string.caseInsensitiveStartsWith=function(a,b){return 0==goog.string.caseInsensitiveCompare(b,a.substr(0,b.length))};goog.string.caseInsensitiveEndsWith=function(a,b){return 0==goog.string.caseInsensitiveCompare(b,a.substr(a.length-b.length,b.length))};
goog.string.caseInsensitiveEquals=function(a,b){return a.toLowerCase()==b.toLowerCase()};goog.string.subs=function(a,b){for(var c=1;c<arguments.length;c++){var d=String(arguments[c]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,d)}return a};goog.string.collapseWhitespace=function(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};goog.string.isEmpty=function(a){return/^[\s\xa0]*$/.test(a)};goog.string.isEmptySafe=function(a){return goog.string.isEmpty(goog.string.makeSafe(a))};
goog.string.isBreakingWhitespace=function(a){return!/[^\t\n\r ]/.test(a)};goog.string.isAlpha=function(a){return!/[^a-zA-Z]/.test(a)};goog.string.isNumeric=function(a){return!/[^0-9]/.test(a)};goog.string.isAlphaNumeric=function(a){return!/[^a-zA-Z0-9]/.test(a)};goog.string.isSpace=function(a){return" "==a};goog.string.isUnicodeChar=function(a){return 1==a.length&&" "<=a&&"~">=a||"\u0080"<=a&&"\ufffd">=a};goog.string.stripNewlines=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")};
goog.string.canonicalizeNewlines=function(a){return a.replace(/(\r\n|\r|\n)/g,"\n")};goog.string.normalizeWhitespace=function(a){return a.replace(/\xa0|\s/g," ")};goog.string.normalizeSpaces=function(a){return a.replace(/\xa0|[ \t]+/g," ")};goog.string.collapseBreakingSpaces=function(a){return a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")};goog.string.trim=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
goog.string.trimLeft=function(a){return a.replace(/^[\s\xa0]+/,"")};goog.string.trimRight=function(a){return a.replace(/[\s\xa0]+$/,"")};goog.string.caseInsensitiveCompare=function(a,b){var c=String(a).toLowerCase(),d=String(b).toLowerCase();return c<d?-1:c==d?0:1};goog.string.numerateCompareRegExp_=/(\.\d+)|(\d+)|(\D+)/g;
goog.string.numerateCompare=function(a,b){if(a==b)return 0;if(!a)return-1;if(!b)return 1;for(var c=a.toLowerCase().match(goog.string.numerateCompareRegExp_),d=b.toLowerCase().match(goog.string.numerateCompareRegExp_),e=Math.min(c.length,d.length),f=0;f<e;f++){var g=c[f],h=d[f];if(g!=h)return c=parseInt(g,10),!isNaN(c)&&(d=parseInt(h,10),!isNaN(d)&&c-d)?c-d:g<h?-1:1}return c.length!=d.length?c.length-d.length:a<b?-1:1};goog.string.urlEncode=function(a){return encodeURIComponent(String(a))};
goog.string.urlDecode=function(a){return decodeURIComponent(a.replace(/\+/g," "))};goog.string.newLineToBr=function(a,b){return a.replace(/(\r\n|\r|\n)/g,b?"<br />":"<br>")};
goog.string.htmlEscape=function(a,b){if(b)return a.replace(goog.string.amperRe_,"&amp;").replace(goog.string.ltRe_,"&lt;").replace(goog.string.gtRe_,"&gt;").replace(goog.string.quotRe_,"&quot;");if(!goog.string.allRe_.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(goog.string.amperRe_,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(goog.string.ltRe_,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(goog.string.gtRe_,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(goog.string.quotRe_,"&quot;"));return a};
goog.string.amperRe_=/&/g;goog.string.ltRe_=/</g;goog.string.gtRe_=/>/g;goog.string.quotRe_=/\"/g;goog.string.allRe_=/[&<>\"]/;goog.string.unescapeEntities=function(a){return goog.string.contains(a,"&")?"document"in goog.global?goog.string.unescapeEntitiesUsingDom_(a):goog.string.unescapePureXmlEntities_(a):a};
goog.string.unescapeEntitiesUsingDom_=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c=document.createElement("div");return a.replace(goog.string.HTML_ENTITY_PATTERN_,function(a,e){var f=b[a];if(f)return f;if("#"==e.charAt(0)){var g=Number("0"+e.substr(1));isNaN(g)||(f=String.fromCharCode(g))}f||(c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1));return b[a]=f})};
goog.string.unescapePureXmlEntities_=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return a}})};goog.string.HTML_ENTITY_PATTERN_=/&([^;\s<&]+);?/g;goog.string.whitespaceEscape=function(a,b){return goog.string.newLineToBr(a.replace(/  /g," &#160;"),b)};
goog.string.stripQuotes=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=1==c?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a};goog.string.truncate=function(a,b,c){c&&(a=goog.string.unescapeEntities(a));a.length>b&&(a=a.substring(0,b-3)+"...");c&&(a=goog.string.htmlEscape(a));return a};
goog.string.truncateMiddle=function(a,b,c,d){c&&(a=goog.string.unescapeEntities(a));if(d&&a.length>b){d>b&&(d=b);var e=a.length-d;a=a.substring(0,b-d)+"..."+a.substring(e)}else a.length>b&&(d=Math.floor(b/2),e=a.length-d,a=a.substring(0,d+b%2)+"..."+a.substring(e));c&&(a=goog.string.htmlEscape(a));return a};goog.string.specialEscapeChars_={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"};goog.string.jsEscapeCache_={"'":"\\'"};
goog.string.quote=function(a){a=String(a);if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0);b[c+1]=goog.string.specialEscapeChars_[d]||(31<e&&127>e?d:goog.string.escapeChar(d))}b.push('"');return b.join("")};goog.string.escapeString=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=goog.string.escapeChar(a.charAt(c));return b.join("")};
goog.string.escapeChar=function(a){if(a in goog.string.jsEscapeCache_)return goog.string.jsEscapeCache_[a];if(a in goog.string.specialEscapeChars_)return goog.string.jsEscapeCache_[a]=goog.string.specialEscapeChars_[a];var b=a,c=a.charCodeAt(0);if(31<c&&127>c)b=a;else{if(256>c){if(b="\\x",16>c||256<c)b+="0"}else b="\\u",4096>c&&(b+="0");b+=c.toString(16).toUpperCase()}return goog.string.jsEscapeCache_[a]=b};goog.string.toMap=function(a){for(var b={},c=0;c<a.length;c++)b[a.charAt(c)]=!0;return b};
goog.string.contains=function(a,b){return-1!=a.indexOf(b)};goog.string.countOf=function(a,b){return a&&b?a.split(b).length-1:0};goog.string.removeAt=function(a,b,c){var d=a;0<=b&&(b<a.length&&0<c)&&(d=a.substr(0,b)+a.substr(b+c,a.length-b-c));return d};goog.string.remove=function(a,b){var c=RegExp(goog.string.regExpEscape(b),"");return a.replace(c,"")};goog.string.removeAll=function(a,b){var c=RegExp(goog.string.regExpEscape(b),"g");return a.replace(c,"")};
goog.string.regExpEscape=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};goog.string.repeat=function(a,b){return Array(b+1).join(a)};goog.string.padNumber=function(a,b,c){a=goog.isDef(c)?a.toFixed(c):String(a);c=a.indexOf(".");-1==c&&(c=a.length);return goog.string.repeat("0",Math.max(0,b-c))+a};goog.string.makeSafe=function(a){return null==a?"":String(a)};goog.string.buildString=function(a){return Array.prototype.join.call(arguments,"")};
goog.string.getRandomString=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^goog.now()).toString(36)};
goog.string.compareVersions=function(a,b){for(var c=0,d=goog.string.trim(String(a)).split("."),e=goog.string.trim(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",l=e[g]||"",k=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var m=k.exec(h)||["","",""],p=n.exec(l)||["","",""];if(0==m[0].length&&0==p[0].length)break;var c=0==m[1].length?0:parseInt(m[1],10),q=0==p[1].length?0:parseInt(p[1],10),c=goog.string.compareElements_(c,q)||goog.string.compareElements_(0==
m[2].length,0==p[2].length)||goog.string.compareElements_(m[2],p[2])}while(0==c)}return c};goog.string.compareElements_=function(a,b){return a<b?-1:a>b?1:0};goog.string.HASHCODE_MAX_=4294967296;goog.string.hashCode=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=goog.string.HASHCODE_MAX_;return b};goog.string.uniqueStringCounter_=2147483648*Math.random()|0;goog.string.createUniqueString=function(){return"goog_"+goog.string.uniqueStringCounter_++};
goog.string.toNumber=function(a){var b=Number(a);return 0==b&&goog.string.isEmpty(a)?NaN:b};goog.string.isLowerCamelCase=function(a){return/^[a-z]+([A-Z][a-z]*)*$/.test(a)};goog.string.isUpperCamelCase=function(a){return/^([A-Z][a-z]*)+$/.test(a)};goog.string.toCamelCase=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};goog.string.toSelectorCase=function(a){return String(a).replace(/([A-Z])/g,"-$1").toLowerCase()};
goog.string.toTitleCase=function(a,b){var c=goog.isString(b)?goog.string.regExpEscape(b):"\\s";return a.replace(RegExp("(^"+(c?"|["+c+"]+":"")+")([a-z])","g"),function(a,b,c){return b+c.toUpperCase()})};goog.string.parseInt=function(a){isFinite(a)&&(a=String(a));return goog.isString(a)?/^\s*-?0x/i.test(a)?parseInt(a,16):parseInt(a,10):NaN};goog.asserts={};goog.asserts.ENABLE_ASSERTS=goog.DEBUG;goog.asserts.AssertionError=function(a,b){b.unshift(a);goog.debug.Error.call(this,goog.string.subs.apply(null,b));b.shift();this.messagePattern=a};goog.inherits(goog.asserts.AssertionError,goog.debug.Error);goog.asserts.AssertionError.prototype.name="AssertionError";goog.asserts.doAssertFailure_=function(a,b,c,d){var e="Assertion failed";if(c)var e=e+(": "+c),f=d;else a&&(e+=": "+a,f=b);throw new goog.asserts.AssertionError(""+e,f||[]);};
goog.asserts.assert=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!a&&goog.asserts.doAssertFailure_("",null,b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.fail=function(a,b){if(goog.asserts.ENABLE_ASSERTS)throw new goog.asserts.AssertionError("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};
goog.asserts.assertNumber=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isNumber(a)&&goog.asserts.doAssertFailure_("Expected number but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertString=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isString(a)&&goog.asserts.doAssertFailure_("Expected string but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertFunction=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isFunction(a)&&goog.asserts.doAssertFailure_("Expected function but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertObject=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isObject(a)&&goog.asserts.doAssertFailure_("Expected object but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertArray=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isArray(a)&&goog.asserts.doAssertFailure_("Expected array but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertBoolean=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isBoolean(a)&&goog.asserts.doAssertFailure_("Expected boolean but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertInstanceof=function(a,b,c,d){!goog.asserts.ENABLE_ASSERTS||a instanceof b||goog.asserts.doAssertFailure_("instanceof check failed.",null,c,Array.prototype.slice.call(arguments,3));return a};goog.events.Listenable=function(){};goog.events.Listenable.IMPLEMENTED_BY_PROP="closure_listenable_"+(1E6*Math.random()|0);goog.events.Listenable.addImplementation=function(a){a.prototype[goog.events.Listenable.IMPLEMENTED_BY_PROP]=!0};goog.events.Listenable.isImplementedBy=function(a){return!(!a||!a[goog.events.Listenable.IMPLEMENTED_BY_PROP])};goog.events.ListenableKey=function(){};goog.events.ListenableKey.counter_=0;goog.events.ListenableKey.reserveKey=function(){return++goog.events.ListenableKey.counter_};goog.events.Listener=function(a,b,c,d,e,f){goog.events.Listener.ENABLE_MONITORING&&(this.creationStack=Error().stack);this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.key=goog.events.ListenableKey.reserveKey();this.removed=this.callOnce=!1};goog.events.Listener.ENABLE_MONITORING=!1;goog.events.Listener.prototype.markAsRemoved=function(){this.removed=!0;this.handler=this.src=this.proxy=this.listener=null};goog.object={};goog.object.forEach=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};goog.object.filter=function(a,b,c){var d={},e;for(e in a)b.call(c,a[e],e,a)&&(d[e]=a[e]);return d};goog.object.map=function(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d};goog.object.some=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return!0;return!1};goog.object.every=function(a,b,c){for(var d in a)if(!b.call(c,a[d],d,a))return!1;return!0};
goog.object.getCount=function(a){var b=0,c;for(c in a)b++;return b};goog.object.getAnyKey=function(a){for(var b in a)return b};goog.object.getAnyValue=function(a){for(var b in a)return a[b]};goog.object.contains=function(a,b){return goog.object.containsValue(a,b)};goog.object.getValues=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};goog.object.getKeys=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
goog.object.getValueByKeys=function(a,b){for(var c=goog.isArrayLike(b),d=c?b:arguments,c=c?0:1;c<d.length&&(a=a[d[c]],goog.isDef(a));c++);return a};goog.object.containsKey=function(a,b){return b in a};goog.object.containsValue=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1};goog.object.findKey=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};goog.object.findValue=function(a,b,c){return(b=goog.object.findKey(a,b,c))&&a[b]};
goog.object.isEmpty=function(a){for(var b in a)return!1;return!0};goog.object.clear=function(a){for(var b in a)delete a[b]};goog.object.remove=function(a,b){var c;(c=b in a)&&delete a[b];return c};goog.object.add=function(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');goog.object.set(a,b,c)};goog.object.get=function(a,b,c){return b in a?a[b]:c};goog.object.set=function(a,b,c){a[b]=c};goog.object.setIfUndefined=function(a,b,c){return b in a?a[b]:a[b]=c};
goog.object.clone=function(a){var b={},c;for(c in a)b[c]=a[c];return b};goog.object.unsafeClone=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=goog.object.unsafeClone(a[c]);return b}return a};goog.object.transpose=function(a){var b={},c;for(c in a)b[a[c]]=c;return b};goog.object.PROTOTYPE_FIELDS_="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
goog.object.extend=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<goog.object.PROTOTYPE_FIELDS_.length;f++)c=goog.object.PROTOTYPE_FIELDS_[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
goog.object.create=function(a){var b=arguments.length;if(1==b&&goog.isArray(arguments[0]))return goog.object.create.apply(null,arguments[0]);if(b%2)throw Error("Uneven number of arguments");for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};goog.object.createSet=function(a){var b=arguments.length;if(1==b&&goog.isArray(arguments[0]))return goog.object.createSet.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
goog.object.createImmutableView=function(a){var b=a;Object.isFrozen&&!Object.isFrozen(a)&&(b=Object.create(a),Object.freeze(b));return b};goog.object.isImmutableView=function(a){return!!Object.isFrozen&&Object.isFrozen(a)};goog.userAgent={};goog.userAgent.ASSUME_IE=!1;goog.userAgent.ASSUME_GECKO=!1;goog.userAgent.ASSUME_WEBKIT=!1;goog.userAgent.ASSUME_MOBILE_WEBKIT=!1;goog.userAgent.ASSUME_OPERA=!1;goog.userAgent.ASSUME_ANY_VERSION=!1;goog.userAgent.BROWSER_KNOWN_=goog.userAgent.ASSUME_IE||goog.userAgent.ASSUME_GECKO||goog.userAgent.ASSUME_MOBILE_WEBKIT||goog.userAgent.ASSUME_WEBKIT||goog.userAgent.ASSUME_OPERA;
goog.userAgent.getUserAgentString=function(){return goog.global.navigator?goog.global.navigator.userAgent:null};goog.userAgent.getNavigator=function(){return goog.global.navigator};
goog.userAgent.init_=function(){goog.userAgent.detectedOpera_=!1;goog.userAgent.detectedIe_=!1;goog.userAgent.detectedWebkit_=!1;goog.userAgent.detectedMobile_=!1;goog.userAgent.detectedGecko_=!1;var a;if(!goog.userAgent.BROWSER_KNOWN_&&(a=goog.userAgent.getUserAgentString())){var b=goog.userAgent.getNavigator();goog.userAgent.detectedOpera_=0==a.indexOf("Opera");goog.userAgent.detectedIe_=!goog.userAgent.detectedOpera_&&-1!=a.indexOf("MSIE");goog.userAgent.detectedWebkit_=!goog.userAgent.detectedOpera_&&
-1!=a.indexOf("WebKit");goog.userAgent.detectedMobile_=goog.userAgent.detectedWebkit_&&-1!=a.indexOf("Mobile");goog.userAgent.detectedGecko_=!goog.userAgent.detectedOpera_&&!goog.userAgent.detectedWebkit_&&"Gecko"==b.product}};goog.userAgent.BROWSER_KNOWN_||goog.userAgent.init_();goog.userAgent.OPERA=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_OPERA:goog.userAgent.detectedOpera_;goog.userAgent.IE=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_IE:goog.userAgent.detectedIe_;
goog.userAgent.GECKO=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_GECKO:goog.userAgent.detectedGecko_;goog.userAgent.WEBKIT=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_WEBKIT||goog.userAgent.ASSUME_MOBILE_WEBKIT:goog.userAgent.detectedWebkit_;goog.userAgent.MOBILE=goog.userAgent.ASSUME_MOBILE_WEBKIT||goog.userAgent.detectedMobile_;goog.userAgent.SAFARI=goog.userAgent.WEBKIT;goog.userAgent.determinePlatform_=function(){var a=goog.userAgent.getNavigator();return a&&a.platform||""};
goog.userAgent.PLATFORM=goog.userAgent.determinePlatform_();goog.userAgent.ASSUME_MAC=!1;goog.userAgent.ASSUME_WINDOWS=!1;goog.userAgent.ASSUME_LINUX=!1;goog.userAgent.ASSUME_X11=!1;goog.userAgent.ASSUME_ANDROID=!1;goog.userAgent.ASSUME_IPHONE=!1;goog.userAgent.ASSUME_IPAD=!1;goog.userAgent.PLATFORM_KNOWN_=goog.userAgent.ASSUME_MAC||goog.userAgent.ASSUME_WINDOWS||goog.userAgent.ASSUME_LINUX||goog.userAgent.ASSUME_X11||goog.userAgent.ASSUME_ANDROID||goog.userAgent.ASSUME_IPHONE||goog.userAgent.ASSUME_IPAD;
goog.userAgent.initPlatform_=function(){goog.userAgent.detectedMac_=goog.string.contains(goog.userAgent.PLATFORM,"Mac");goog.userAgent.detectedWindows_=goog.string.contains(goog.userAgent.PLATFORM,"Win");goog.userAgent.detectedLinux_=goog.string.contains(goog.userAgent.PLATFORM,"Linux");goog.userAgent.detectedX11_=!!goog.userAgent.getNavigator()&&goog.string.contains(goog.userAgent.getNavigator().appVersion||"","X11");var a=goog.userAgent.getUserAgentString();goog.userAgent.detectedAndroid_=!!a&&
0<=a.indexOf("Android");goog.userAgent.detectedIPhone_=!!a&&0<=a.indexOf("iPhone");goog.userAgent.detectedIPad_=!!a&&0<=a.indexOf("iPad")};goog.userAgent.PLATFORM_KNOWN_||goog.userAgent.initPlatform_();goog.userAgent.MAC=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_MAC:goog.userAgent.detectedMac_;goog.userAgent.WINDOWS=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_WINDOWS:goog.userAgent.detectedWindows_;
goog.userAgent.LINUX=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_LINUX:goog.userAgent.detectedLinux_;goog.userAgent.X11=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_X11:goog.userAgent.detectedX11_;goog.userAgent.ANDROID=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_ANDROID:goog.userAgent.detectedAndroid_;goog.userAgent.IPHONE=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_IPHONE:goog.userAgent.detectedIPhone_;
goog.userAgent.IPAD=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_IPAD:goog.userAgent.detectedIPad_;
goog.userAgent.determineVersion_=function(){var a="",b;goog.userAgent.OPERA&&goog.global.opera?(a=goog.global.opera.version,a="function"==typeof a?a():a):(goog.userAgent.GECKO?b=/rv\:([^\);]+)(\)|;)/:goog.userAgent.IE?b=/MSIE\s+([^\);]+)(\)|;)/:goog.userAgent.WEBKIT&&(b=/WebKit\/(\S+)/),b&&(a=(a=b.exec(goog.userAgent.getUserAgentString()))?a[1]:""));return goog.userAgent.IE&&(b=goog.userAgent.getDocumentMode_(),b>parseFloat(a))?String(b):a};
goog.userAgent.getDocumentMode_=function(){var a=goog.global.document;return a?a.documentMode:void 0};goog.userAgent.VERSION=goog.userAgent.determineVersion_();goog.userAgent.compare=function(a,b){return goog.string.compareVersions(a,b)};goog.userAgent.isVersionOrHigherCache_={};
goog.userAgent.isVersionOrHigher=function(a){return goog.userAgent.ASSUME_ANY_VERSION||goog.userAgent.isVersionOrHigherCache_[a]||(goog.userAgent.isVersionOrHigherCache_[a]=0<=goog.string.compareVersions(goog.userAgent.VERSION,a))};goog.userAgent.isVersion=goog.userAgent.isVersionOrHigher;goog.userAgent.isDocumentModeOrHigher=function(a){return goog.userAgent.IE&&goog.userAgent.DOCUMENT_MODE>=a};goog.userAgent.isDocumentMode=goog.userAgent.isDocumentModeOrHigher;
goog.userAgent.DOCUMENT_MODE=function(){var a=goog.global.document;return a&&goog.userAgent.IE?goog.userAgent.getDocumentMode_()||("CSS1Compat"==a.compatMode?parseInt(goog.userAgent.VERSION,10):5):void 0}();goog.events.BrowserFeature={HAS_W3C_BUTTON:!goog.userAgent.IE||goog.userAgent.isDocumentModeOrHigher(9),HAS_W3C_EVENT_SUPPORT:!goog.userAgent.IE||goog.userAgent.isDocumentModeOrHigher(9),SET_KEY_CODE_TO_PREVENT_DEFAULT:goog.userAgent.IE&&!goog.userAgent.isVersionOrHigher("9"),HAS_NAVIGATOR_ONLINE_PROPERTY:!goog.userAgent.WEBKIT||goog.userAgent.isVersionOrHigher("528"),HAS_HTML5_NETWORK_EVENT_SUPPORT:goog.userAgent.GECKO&&goog.userAgent.isVersionOrHigher("1.9b")||goog.userAgent.IE&&goog.userAgent.isVersionOrHigher("8")||
goog.userAgent.OPERA&&goog.userAgent.isVersionOrHigher("9.5")||goog.userAgent.WEBKIT&&goog.userAgent.isVersionOrHigher("528"),HTML5_NETWORK_EVENTS_FIRE_ON_BODY:goog.userAgent.GECKO&&!goog.userAgent.isVersionOrHigher("8")||goog.userAgent.IE&&!goog.userAgent.isVersionOrHigher("9"),TOUCH_ENABLED:"ontouchstart"in goog.global||!!(goog.global.document&&document.documentElement&&"ontouchstart"in document.documentElement)||!(!goog.global.navigator||!goog.global.navigator.msMaxTouchPoints)};goog.array={};goog.NATIVE_ARRAY_PROTOTYPES=goog.TRUSTED_SITE;goog.array.peek=function(a){return a[a.length-1]};goog.array.ARRAY_PROTOTYPE_=Array.prototype;
goog.array.indexOf=goog.NATIVE_ARRAY_PROTOTYPES&&goog.array.ARRAY_PROTOTYPE_.indexOf?function(a,b,c){goog.asserts.assert(null!=a.length);return goog.array.ARRAY_PROTOTYPE_.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(goog.isString(a))return goog.isString(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
goog.array.lastIndexOf=goog.NATIVE_ARRAY_PROTOTYPES&&goog.array.ARRAY_PROTOTYPE_.lastIndexOf?function(a,b,c){goog.asserts.assert(null!=a.length);return goog.array.ARRAY_PROTOTYPE_.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(goog.isString(a))return goog.isString(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
goog.array.forEach=goog.NATIVE_ARRAY_PROTOTYPES&&goog.array.ARRAY_PROTOTYPE_.forEach?function(a,b,c){goog.asserts.assert(null!=a.length);goog.array.ARRAY_PROTOTYPE_.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=goog.isString(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};goog.array.forEachRight=function(a,b,c){for(var d=a.length,e=goog.isString(a)?a.split(""):a,d=d-1;0<=d;--d)d in e&&b.call(c,e[d],d,a)};
goog.array.filter=goog.NATIVE_ARRAY_PROTOTYPES&&goog.array.ARRAY_PROTOTYPE_.filter?function(a,b,c){goog.asserts.assert(null!=a.length);return goog.array.ARRAY_PROTOTYPE_.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=goog.isString(a)?a.split(""):a,h=0;h<d;h++)if(h in g){var l=g[h];b.call(c,l,h,a)&&(e[f++]=l)}return e};
goog.array.map=goog.NATIVE_ARRAY_PROTOTYPES&&goog.array.ARRAY_PROTOTYPE_.map?function(a,b,c){goog.asserts.assert(null!=a.length);return goog.array.ARRAY_PROTOTYPE_.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=goog.isString(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};goog.array.reduce=function(a,b,c,d){if(a.reduce)return d?a.reduce(goog.bind(b,d),c):a.reduce(b,c);var e=c;goog.array.forEach(a,function(c,g){e=b.call(d,e,c,g,a)});return e};
goog.array.reduceRight=function(a,b,c,d){if(a.reduceRight)return d?a.reduceRight(goog.bind(b,d),c):a.reduceRight(b,c);var e=c;goog.array.forEachRight(a,function(c,g){e=b.call(d,e,c,g,a)});return e};
goog.array.some=goog.NATIVE_ARRAY_PROTOTYPES&&goog.array.ARRAY_PROTOTYPE_.some?function(a,b,c){goog.asserts.assert(null!=a.length);return goog.array.ARRAY_PROTOTYPE_.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=goog.isString(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
goog.array.every=goog.NATIVE_ARRAY_PROTOTYPES&&goog.array.ARRAY_PROTOTYPE_.every?function(a,b,c){goog.asserts.assert(null!=a.length);return goog.array.ARRAY_PROTOTYPE_.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=goog.isString(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};goog.array.count=function(a,b,c){var d=0;goog.array.forEach(a,function(a,f,g){b.call(c,a,f,g)&&++d},c);return d};
goog.array.find=function(a,b,c){b=goog.array.findIndex(a,b,c);return 0>b?null:goog.isString(a)?a.charAt(b):a[b]};goog.array.findIndex=function(a,b,c){for(var d=a.length,e=goog.isString(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};goog.array.findRight=function(a,b,c){b=goog.array.findIndexRight(a,b,c);return 0>b?null:goog.isString(a)?a.charAt(b):a[b]};
goog.array.findIndexRight=function(a,b,c){for(var d=a.length,e=goog.isString(a)?a.split(""):a,d=d-1;0<=d;d--)if(d in e&&b.call(c,e[d],d,a))return d;return-1};goog.array.contains=function(a,b){return 0<=goog.array.indexOf(a,b)};goog.array.isEmpty=function(a){return 0==a.length};goog.array.clear=function(a){if(!goog.isArray(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0};goog.array.insert=function(a,b){goog.array.contains(a,b)||a.push(b)};
goog.array.insertAt=function(a,b,c){goog.array.splice(a,c,0,b)};goog.array.insertArrayAt=function(a,b,c){goog.partial(goog.array.splice,a,c,0).apply(null,b)};goog.array.insertBefore=function(a,b,c){var d;2==arguments.length||0>(d=goog.array.indexOf(a,c))?a.push(b):goog.array.insertAt(a,b,d)};goog.array.remove=function(a,b){var c=goog.array.indexOf(a,b),d;(d=0<=c)&&goog.array.removeAt(a,c);return d};
goog.array.removeAt=function(a,b){goog.asserts.assert(null!=a.length);return 1==goog.array.ARRAY_PROTOTYPE_.splice.call(a,b,1).length};goog.array.removeIf=function(a,b,c){b=goog.array.findIndex(a,b,c);return 0<=b?(goog.array.removeAt(a,b),!0):!1};goog.array.concat=function(a){return goog.array.ARRAY_PROTOTYPE_.concat.apply(goog.array.ARRAY_PROTOTYPE_,arguments)};goog.array.toArray=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};goog.array.clone=goog.array.toArray;
goog.array.extend=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(goog.isArray(d)||(e=goog.isArrayLike(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,g=d.length,h=0;h<g;h++)a[f+h]=d[h];else a.push(d)}};goog.array.splice=function(a,b,c,d){goog.asserts.assert(null!=a.length);return goog.array.ARRAY_PROTOTYPE_.splice.apply(a,goog.array.slice(arguments,1))};
goog.array.slice=function(a,b,c){goog.asserts.assert(null!=a.length);return 2>=arguments.length?goog.array.ARRAY_PROTOTYPE_.slice.call(a,b):goog.array.ARRAY_PROTOTYPE_.slice.call(a,b,c)};goog.array.removeDuplicates=function(a,b){for(var c=b||a,d={},e=0,f=0;f<a.length;){var g=a[f++],h=goog.isObject(g)?"o"+goog.getUid(g):(typeof g).charAt(0)+g;Object.prototype.hasOwnProperty.call(d,h)||(d[h]=!0,c[e++]=g)}c.length=e};
goog.array.binarySearch=function(a,b,c){return goog.array.binarySearch_(a,c||goog.array.defaultCompare,!1,b)};goog.array.binarySelect=function(a,b,c){return goog.array.binarySearch_(a,b,!0,void 0,c)};goog.array.binarySearch_=function(a,b,c,d,e){for(var f=0,g=a.length,h;f<g;){var l=f+g>>1,k;k=c?b.call(e,a[l],l,a):b(d,a[l]);0<k?f=l+1:(g=l,h=!k)}return h?f:~f};goog.array.sort=function(a,b){goog.asserts.assert(null!=a.length);goog.array.ARRAY_PROTOTYPE_.sort.call(a,b||goog.array.defaultCompare)};
goog.array.stableSort=function(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var d=b||goog.array.defaultCompare;goog.array.sort(a,function(a,b){return d(a.value,b.value)||a.index-b.index});for(c=0;c<a.length;c++)a[c]=a[c].value};goog.array.sortObjectsByKey=function(a,b,c){var d=c||goog.array.defaultCompare;goog.array.sort(a,function(a,c){return d(a[b],c[b])})};
goog.array.isSorted=function(a,b,c){b=b||goog.array.defaultCompare;for(var d=1;d<a.length;d++){var e=b(a[d-1],a[d]);if(0<e||0==e&&c)return!1}return!0};goog.array.equals=function(a,b,c){if(!goog.isArrayLike(a)||!goog.isArrayLike(b)||a.length!=b.length)return!1;var d=a.length;c=c||goog.array.defaultCompareEquality;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return!1;return!0};goog.array.compare=function(a,b,c){return goog.array.equals(a,b,c)};
goog.array.compare3=function(a,b,c){c=c||goog.array.defaultCompare;for(var d=Math.min(a.length,b.length),e=0;e<d;e++){var f=c(a[e],b[e]);if(0!=f)return f}return goog.array.defaultCompare(a.length,b.length)};goog.array.defaultCompare=function(a,b){return a>b?1:a<b?-1:0};goog.array.defaultCompareEquality=function(a,b){return a===b};goog.array.binaryInsert=function(a,b,c){c=goog.array.binarySearch(a,b,c);return 0>c?(goog.array.insertAt(a,b,-(c+1)),!0):!1};
goog.array.binaryRemove=function(a,b,c){b=goog.array.binarySearch(a,b,c);return 0<=b?goog.array.removeAt(a,b):!1};goog.array.bucket=function(a,b,c){for(var d={},e=0;e<a.length;e++){var f=a[e],g=b.call(c,f,e,a);goog.isDef(g)&&(d[g]||(d[g]=[])).push(f)}return d};goog.array.toObject=function(a,b,c){var d={};goog.array.forEach(a,function(e,f){d[b.call(c,e,f,a)]=e});return d};
goog.array.range=function(a,b,c){var d=[],e=0,f=a;c=c||1;void 0!==b&&(e=a,f=b);if(0>c*(f-e))return[];if(0<c)for(a=e;a<f;a+=c)d.push(a);else for(a=e;a>f;a+=c)d.push(a);return d};goog.array.repeat=function(a,b){for(var c=[],d=0;d<b;d++)c[d]=a;return c};goog.array.flatten=function(a){for(var b=[],c=0;c<arguments.length;c++){var d=arguments[c];goog.isArray(d)?b.push.apply(b,goog.array.flatten.apply(null,d)):b.push(d)}return b};
goog.array.rotate=function(a,b){goog.asserts.assert(null!=a.length);a.length&&(b%=a.length,0<b?goog.array.ARRAY_PROTOTYPE_.unshift.apply(a,a.splice(-b,b)):0>b&&goog.array.ARRAY_PROTOTYPE_.push.apply(a,a.splice(0,-b)));return a};goog.array.zip=function(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}};
goog.array.shuffle=function(a,b){for(var c=b||Math.random,d=a.length-1;0<d;d--){var e=Math.floor(c()*(d+1)),f=a[d];a[d]=a[e];a[e]=f}};goog.debug.entryPointRegistry={};goog.debug.EntryPointMonitor=function(){};goog.debug.entryPointRegistry.refList_=[];goog.debug.entryPointRegistry.monitors_=[];goog.debug.entryPointRegistry.monitorsMayExist_=!1;goog.debug.entryPointRegistry.register=function(a){goog.debug.entryPointRegistry.refList_[goog.debug.entryPointRegistry.refList_.length]=a;if(goog.debug.entryPointRegistry.monitorsMayExist_)for(var b=goog.debug.entryPointRegistry.monitors_,c=0;c<b.length;c++)a(goog.bind(b[c].wrap,b[c]))};
goog.debug.entryPointRegistry.monitorAll=function(a){goog.debug.entryPointRegistry.monitorsMayExist_=!0;for(var b=goog.bind(a.wrap,a),c=0;c<goog.debug.entryPointRegistry.refList_.length;c++)goog.debug.entryPointRegistry.refList_[c](b);goog.debug.entryPointRegistry.monitors_.push(a)};
goog.debug.entryPointRegistry.unmonitorAllIfPossible=function(a){var b=goog.debug.entryPointRegistry.monitors_;goog.asserts.assert(a==b[b.length-1],"Only the most recent monitor can be unwrapped.");a=goog.bind(a.unwrap,a);for(var c=0;c<goog.debug.entryPointRegistry.refList_.length;c++)goog.debug.entryPointRegistry.refList_[c](a);b.length--};goog.events.EventType={CLICK:"click",DBLCLICK:"dblclick",MOUSEDOWN:"mousedown",MOUSEUP:"mouseup",MOUSEOVER:"mouseover",MOUSEOUT:"mouseout",MOUSEMOVE:"mousemove",SELECTSTART:"selectstart",KEYPRESS:"keypress",KEYDOWN:"keydown",KEYUP:"keyup",BLUR:"blur",FOCUS:"focus",DEACTIVATE:"deactivate",FOCUSIN:goog.userAgent.IE?"focusin":"DOMFocusIn",FOCUSOUT:goog.userAgent.IE?"focusout":"DOMFocusOut",CHANGE:"change",SELECT:"select",SUBMIT:"submit",INPUT:"input",PROPERTYCHANGE:"propertychange",DRAGSTART:"dragstart",
DRAG:"drag",DRAGENTER:"dragenter",DRAGOVER:"dragover",DRAGLEAVE:"dragleave",DROP:"drop",DRAGEND:"dragend",TOUCHSTART:"touchstart",TOUCHMOVE:"touchmove",TOUCHEND:"touchend",TOUCHCANCEL:"touchcancel",BEFOREUNLOAD:"beforeunload",CONTEXTMENU:"contextmenu",DOMCONTENTLOADED:"DOMContentLoaded",ERROR:"error",HELP:"help",LOAD:"load",LOSECAPTURE:"losecapture",READYSTATECHANGE:"readystatechange",RESIZE:"resize",SCROLL:"scroll",UNLOAD:"unload",HASHCHANGE:"hashchange",PAGEHIDE:"pagehide",PAGESHOW:"pageshow",POPSTATE:"popstate",
COPY:"copy",PASTE:"paste",CUT:"cut",BEFORECOPY:"beforecopy",BEFORECUT:"beforecut",BEFOREPASTE:"beforepaste",ONLINE:"online",OFFLINE:"offline",MESSAGE:"message",CONNECT:"connect",TRANSITIONEND:goog.userAgent.WEBKIT?"webkitTransitionEnd":goog.userAgent.OPERA?"oTransitionEnd":"transitionend",MSGESTURECHANGE:"MSGestureChange",MSGESTUREEND:"MSGestureEnd",MSGESTUREHOLD:"MSGestureHold",MSGESTURESTART:"MSGestureStart",MSGESTURETAP:"MSGestureTap",MSGOTPOINTERCAPTURE:"MSGotPointerCapture",MSINERTIASTART:"MSInertiaStart",
MSLOSTPOINTERCAPTURE:"MSLostPointerCapture",MSPOINTERCANCEL:"MSPointerCancel",MSPOINTERDOWN:"MSPointerDown",MSPOINTERMOVE:"MSPointerMove",MSPOINTEROVER:"MSPointerOver",MSPOINTEROUT:"MSPointerOut",MSPOINTERUP:"MSPointerUp",TEXTINPUT:"textinput",COMPOSITIONSTART:"compositionstart",COMPOSITIONUPDATE:"compositionupdate",COMPOSITIONEND:"compositionend"};goog.reflect={};goog.reflect.object=function(a,b){return b};goog.reflect.sinkValue=function(a){goog.reflect.sinkValue[" "](a);return a};goog.reflect.sinkValue[" "]=goog.nullFunction;goog.reflect.canAccessProperty=function(a,b){try{return goog.reflect.sinkValue(a[b]),!0}catch(c){}return!1};goog.events.BrowserEvent=function(a,b){a&&this.init(a,b)};goog.inherits(goog.events.BrowserEvent,goog.events.Event);goog.events.BrowserEvent.MouseButton={LEFT:0,MIDDLE:1,RIGHT:2};goog.events.BrowserEvent.IEButtonMap=[1,4,2];goog.events.BrowserEvent.prototype.target=null;goog.events.BrowserEvent.prototype.relatedTarget=null;goog.events.BrowserEvent.prototype.offsetX=0;goog.events.BrowserEvent.prototype.offsetY=0;goog.events.BrowserEvent.prototype.clientX=0;
goog.events.BrowserEvent.prototype.clientY=0;goog.events.BrowserEvent.prototype.screenX=0;goog.events.BrowserEvent.prototype.screenY=0;goog.events.BrowserEvent.prototype.button=0;goog.events.BrowserEvent.prototype.keyCode=0;goog.events.BrowserEvent.prototype.charCode=0;goog.events.BrowserEvent.prototype.ctrlKey=!1;goog.events.BrowserEvent.prototype.altKey=!1;goog.events.BrowserEvent.prototype.shiftKey=!1;goog.events.BrowserEvent.prototype.metaKey=!1;
goog.events.BrowserEvent.prototype.platformModifierKey=!1;goog.events.BrowserEvent.prototype.event_=null;
goog.events.BrowserEvent.prototype.init=function(a,b){var c=this.type=a.type;goog.events.Event.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;d?goog.userAgent.GECKO&&(goog.reflect.canAccessProperty(d,"nodeName")||(d=null)):c==goog.events.EventType.MOUSEOVER?d=a.fromElement:c==goog.events.EventType.MOUSEOUT&&(d=a.toElement);this.relatedTarget=d;this.offsetX=goog.userAgent.WEBKIT||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=goog.userAgent.WEBKIT||void 0!==
a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.platformModifierKey=goog.userAgent.MAC?a.metaKey:a.ctrlKey;this.state=a.state;this.event_=a;a.defaultPrevented&&this.preventDefault();
delete this.propagationStopped_};goog.events.BrowserEvent.prototype.isButton=function(a){return goog.events.BrowserFeature.HAS_W3C_BUTTON?this.event_.button==a:"click"==this.type?a==goog.events.BrowserEvent.MouseButton.LEFT:!!(this.event_.button&goog.events.BrowserEvent.IEButtonMap[a])};goog.events.BrowserEvent.prototype.isMouseActionButton=function(){return this.isButton(goog.events.BrowserEvent.MouseButton.LEFT)&&!(goog.userAgent.WEBKIT&&goog.userAgent.MAC&&this.ctrlKey)};
goog.events.BrowserEvent.prototype.stopPropagation=function(){goog.events.BrowserEvent.superClass_.stopPropagation.call(this);this.event_.stopPropagation?this.event_.stopPropagation():this.event_.cancelBubble=!0};
goog.events.BrowserEvent.prototype.preventDefault=function(){goog.events.BrowserEvent.superClass_.preventDefault.call(this);var a=this.event_;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,goog.events.BrowserFeature.SET_KEY_CODE_TO_PREVENT_DEFAULT)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};goog.events.BrowserEvent.prototype.getBrowserEvent=function(){return this.event_};goog.events.BrowserEvent.prototype.disposeInternal=function(){};goog.events.listeners_={};goog.events.listenerTree_={};goog.events.sources_={};goog.events.onString_="on";goog.events.onStringMap_={};goog.events.keySeparator_="_";goog.events.listen=function(a,b,c,d,e){if(goog.isArray(b)){for(var f=0;f<b.length;f++)goog.events.listen(a,b[f],c,d,e);return null}c=goog.events.wrapListener_(c);return goog.events.Listenable.isImplementedBy(a)?a.listen(b,c,d,e):goog.events.listen_(a,b,c,!1,d,e)};
goog.events.listen_=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");e=!!e;var g=goog.events.listenerTree_;b in g||(g[b]={count_:0,remaining_:0});g=g[b];e in g||(g[e]={count_:0,remaining_:0},g.count_++);var g=g[e],h=goog.getUid(a),l;g.remaining_++;if(g[h]){l=g[h];for(var k=0;k<l.length;k++)if(g=l[k],g.listener==c&&g.handler==f){if(g.removed)break;d||(l[k].callOnce=!1);return l[k]}}else l=g[h]=[],g.count_++;k=goog.events.getProxy();g=new goog.events.Listener(c,k,a,b,e,f);g.callOnce=d;
k.src=a;k.listener=g;l.push(g);goog.events.sources_[h]||(goog.events.sources_[h]=[]);goog.events.sources_[h].push(g);a.addEventListener?a.addEventListener(b,k,e):a.attachEvent(goog.events.getOnString_(b),k);return goog.events.listeners_[g.key]=g};goog.events.getProxy=function(){var a=goog.events.handleBrowserEvent_,b=goog.events.BrowserFeature.HAS_W3C_EVENT_SUPPORT?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
goog.events.listenOnce=function(a,b,c,d,e){if(goog.isArray(b)){for(var f=0;f<b.length;f++)goog.events.listenOnce(a,b[f],c,d,e);return null}c=goog.events.wrapListener_(c);return goog.events.Listenable.isImplementedBy(a)?a.listenOnce(b,c,d,e):goog.events.listen_(a,b,c,!0,d,e)};goog.events.listenWithWrapper=function(a,b,c,d,e){b.listen(a,c,d,e)};
goog.events.unlisten=function(a,b,c,d,e){if(goog.isArray(b)){for(var f=0;f<b.length;f++)goog.events.unlisten(a,b[f],c,d,e);return null}c=goog.events.wrapListener_(c);if(goog.events.Listenable.isImplementedBy(a))return a.unlisten(b,c,d,e);d=!!d;a=goog.events.getListeners_(a,b,d);if(!a)return!1;for(f=0;f<a.length;f++)if(a[f].listener==c&&a[f].capture==d&&a[f].handler==e)return goog.events.unlistenByKey(a[f]);return!1};
goog.events.unlistenByKey=function(a){if(goog.isNumber(a)||!a||a.removed)return!1;var b=a.src;if(goog.events.Listenable.isImplementedBy(b))return b.unlistenByKey(a);var c=a.type,d=a.proxy,e=a.capture;b.removeEventListener?b.removeEventListener(c,d,e):b.detachEvent&&b.detachEvent(goog.events.getOnString_(c),d);b=goog.getUid(b);goog.events.sources_[b]&&(d=goog.events.sources_[b],goog.array.remove(d,a),0==d.length&&delete goog.events.sources_[b]);a.markAsRemoved();if(d=goog.events.listenerTree_[c][e][b])d.needsCleanup_=
!0,goog.events.cleanUp_(c,e,b,d);delete goog.events.listeners_[a.key];return!0};goog.events.unlistenWithWrapper=function(a,b,c,d,e){b.unlisten(a,c,d,e)};goog.events.cleanUp=function(a){delete goog.events.listeners_[a.key]};
goog.events.cleanUp_=function(a,b,c,d){if(!d.locked_&&d.needsCleanup_){for(var e=0,f=0;e<d.length;e++)d[e].removed||(e!=f&&(d[f]=d[e]),f++);d.length=f;d.needsCleanup_=!1;0==f&&(delete goog.events.listenerTree_[a][b][c],goog.events.listenerTree_[a][b].count_--,0==goog.events.listenerTree_[a][b].count_&&(delete goog.events.listenerTree_[a][b],goog.events.listenerTree_[a].count_--),0==goog.events.listenerTree_[a].count_&&delete goog.events.listenerTree_[a])}};
goog.events.removeAll=function(a,b){var c=0,d=null==b;if(null!=a){if(a&&goog.events.Listenable.isImplementedBy(a))return a.removeAllListeners(b);var e=goog.getUid(a);if(goog.events.sources_[e])for(var e=goog.events.sources_[e],f=e.length-1;0<=f;f--){var g=e[f];if(d||b==g.type)goog.events.unlistenByKey(g),c++}}else goog.object.forEach(goog.events.listeners_,function(a){goog.events.unlistenByKey(a);c++});return c};
goog.events.removeAllNativeListeners=function(){var a=0;goog.object.forEach(goog.events.listeners_,function(b){goog.events.Listenable.isImplementedBy(b.src)||(goog.events.unlistenByKey(b),a++)});return a};goog.events.getListeners=function(a,b,c){return goog.events.Listenable.isImplementedBy(a)?a.getListeners(b,c):goog.events.getListeners_(a,b,c)||[]};goog.events.getListeners_=function(a,b,c){var d=goog.events.listenerTree_;return b in d&&(d=d[b],c in d&&(d=d[c],a=goog.getUid(a),d[a]))?d[a]:null};
goog.events.getListener=function(a,b,c,d,e){d=!!d;c=goog.events.wrapListener_(c);if(goog.events.Listenable.isImplementedBy(a))return a.getListener(b,c,d,e);if(a=goog.events.getListeners_(a,b,d))for(b=0;b<a.length;b++)if(!a[b].removed&&a[b].listener==c&&a[b].capture==d&&a[b].handler==e)return a[b];return null};
goog.events.hasListener=function(a,b,c){if(goog.events.Listenable.isImplementedBy(a))return a.hasListener(b,c);a=goog.getUid(a);var d=goog.events.sources_[a];if(d){var e=goog.isDef(b),f=goog.isDef(c);return e&&f?(d=goog.events.listenerTree_[b],!!d&&!!d[c]&&a in d[c]):e||f?goog.array.some(d,function(a){return e&&a.type==b||f&&a.capture==c}):!0}return!1};goog.events.expose=function(a){var b=[],c;for(c in a)a[c]&&a[c].id?b.push(c+" = "+a[c]+" ("+a[c].id+")"):b.push(c+" = "+a[c]);return b.join("\n")};
goog.events.getOnString_=function(a){return a in goog.events.onStringMap_?goog.events.onStringMap_[a]:goog.events.onStringMap_[a]=goog.events.onString_+a};goog.events.fireListeners=function(a,b,c,d){if(goog.events.Listenable.isImplementedBy(a))return a.fireListeners(b,c,d);var e=goog.events.listenerTree_;return b in e&&(e=e[b],c in e)?goog.events.fireListeners_(e[c],a,b,c,d):!0};
goog.events.fireListeners_=function(a,b,c,d,e){var f=1;b=goog.getUid(b);if(a[b]){var g=--a.remaining_,h=a[b];h.locked_?h.locked_++:h.locked_=1;try{for(var l=h.length,k=0;k<l;k++){var n=h[k];n&&!n.removed&&(f&=!1!==goog.events.fireListener(n,e))}}finally{a.remaining_=Math.max(g,a.remaining_),h.locked_--,goog.events.cleanUp_(c,d,b,h)}}return Boolean(f)};goog.events.fireListener=function(a,b){var c=a.listener,d=a.handler||a.src;a.callOnce&&goog.events.unlistenByKey(a);return c.call(d,b)};
goog.events.getTotalListenerCount=function(){return goog.object.getCount(goog.events.listeners_)};goog.events.dispatchEvent=function(a,b){goog.asserts.assert(goog.events.Listenable.isImplementedBy(a),"Can not use goog.events.dispatchEvent with non-goog.events.Listenable instance.");return a.dispatchEvent(b)};goog.events.protectBrowserEventEntryPoint=function(a){goog.events.handleBrowserEvent_=a.protectEntryPoint(goog.events.handleBrowserEvent_)};
goog.events.handleBrowserEvent_=function(a,b){if(a.removed)return!0;var c=a.type,d=goog.events.listenerTree_;if(!(c in d))return!0;var d=d[c],e,f;if(!goog.events.BrowserFeature.HAS_W3C_EVENT_SUPPORT){e=b||goog.getObjectByName("window.event");var g=!0 in d,h=!1 in d;if(g){if(goog.events.isMarkedIeEvent_(e))return!0;goog.events.markIeEvent_(e)}var l=new goog.events.BrowserEvent;l.init(e,this);e=!0;try{if(g){for(var k=[],n=l.currentTarget;n;n=n.parentNode)k.push(n);f=d[!0];f.remaining_=f.count_;for(var m=
k.length-1;!l.propagationStopped_&&0<=m&&f.remaining_;m--)l.currentTarget=k[m],e&=goog.events.fireListeners_(f,k[m],c,!0,l);if(h)for(f=d[!1],f.remaining_=f.count_,m=0;!l.propagationStopped_&&m<k.length&&f.remaining_;m++)l.currentTarget=k[m],e&=goog.events.fireListeners_(f,k[m],c,!1,l)}else e=goog.events.fireListener(a,l)}finally{k&&(k.length=0)}return e}c=new goog.events.BrowserEvent(b,this);return e=goog.events.fireListener(a,c)};
goog.events.markIeEvent_=function(a){var b=!1;if(0==a.keyCode)try{a.keyCode=-1;return}catch(c){b=!0}if(b||void 0==a.returnValue)a.returnValue=!0};goog.events.isMarkedIeEvent_=function(a){return 0>a.keyCode||void 0!=a.returnValue};goog.events.uniqueIdCounter_=0;goog.events.getUniqueId=function(a){return a+"_"+goog.events.uniqueIdCounter_++};goog.events.LISTENER_WRAPPER_PROP_="__closure_events_fn_"+(1E9*Math.random()>>>0);
goog.events.wrapListener_=function(a){goog.asserts.assert(a,"Listener can not be null.");if(goog.isFunction(a))return a;goog.asserts.assert(a.handleEvent,"An object listener must have handleEvent method.");return a[goog.events.LISTENER_WRAPPER_PROP_]||(a[goog.events.LISTENER_WRAPPER_PROP_]=function(b){return a.handleEvent(b)})};goog.debug.entryPointRegistry.register(function(a){goog.events.handleBrowserEvent_=a(goog.events.handleBrowserEvent_)});goog.events.EventTarget=function(){goog.Disposable.call(this);this.eventTargetListeners_={};this.actualEventTarget_=this};goog.inherits(goog.events.EventTarget,goog.Disposable);goog.events.Listenable.addImplementation(goog.events.EventTarget);goog.events.EventTarget.MAX_ANCESTORS_=1E3;goog.events.EventTarget.prototype.parentEventTarget_=null;goog.events.EventTarget.prototype.getParentEventTarget=function(){return this.parentEventTarget_};
goog.events.EventTarget.prototype.setParentEventTarget=function(a){this.parentEventTarget_=a};goog.events.EventTarget.prototype.addEventListener=function(a,b,c,d){goog.events.listen(this,a,b,c,d)};goog.events.EventTarget.prototype.removeEventListener=function(a,b,c,d){goog.events.unlisten(this,a,b,c,d)};
goog.events.EventTarget.prototype.dispatchEvent=function(a){this.assertInitialized_();var b,c=this.getParentEventTarget();if(c){b=[];for(var d=1;c;c=c.getParentEventTarget())b.push(c),goog.asserts.assert(++d<goog.events.EventTarget.MAX_ANCESTORS_,"infinite loop")}return goog.events.EventTarget.dispatchEventInternal_(this.actualEventTarget_,a,b)};
goog.events.EventTarget.prototype.disposeInternal=function(){goog.events.EventTarget.superClass_.disposeInternal.call(this);this.removeAllListeners();this.parentEventTarget_=null};goog.events.EventTarget.prototype.assertInitialized_=function(){goog.asserts.assert(this.eventTargetListeners_,"Event target is not initialized. Did you call superclass (goog.events.EventTarget) constructor?")};goog.events.EventTarget.prototype.listen=function(a,b,c,d){return this.listenInternal_(a,b,!1,c,d)};
goog.events.EventTarget.prototype.listenOnce=function(a,b,c,d){return this.listenInternal_(a,b,!0,c,d)};goog.events.EventTarget.prototype.listenInternal_=function(a,b,c,d,e){this.assertInitialized_();var f=this.eventTargetListeners_[a]||(this.eventTargetListeners_[a]=[]),g=goog.events.EventTarget.findListenerIndex_(f,b,d,e);if(-1<g)return a=f[g],c||(a.callOnce=!1),a;a=new goog.events.Listener(b,null,this,a,!!d,e);a.callOnce=c;f.push(a);return a};
goog.events.EventTarget.prototype.unlisten=function(a,b,c,d){if(!(a in this.eventTargetListeners_))return!1;a=this.eventTargetListeners_[a];b=goog.events.EventTarget.findListenerIndex_(a,b,c,d);return-1<b?(c=a[b],goog.events.cleanUp(c),c.removed=!0,goog.array.removeAt(a,b)):!1};goog.events.EventTarget.prototype.unlistenByKey=function(a){var b=a.type;if(!(b in this.eventTargetListeners_))return!1;if(b=goog.array.remove(this.eventTargetListeners_[b],a))goog.events.cleanUp(a),a.removed=!0;return b};
goog.events.EventTarget.prototype.removeAllListeners=function(a,b){var c=0,d;for(d in this.eventTargetListeners_)if(!a||d==a){for(var e=this.eventTargetListeners_[d],f=0;f<e.length;f++)++c,goog.events.cleanUp(e[f]),e[f].removed=!0;e.length=0}return c};
goog.events.EventTarget.prototype.fireListeners=function(a,b,c){if(!(a in this.eventTargetListeners_))return!0;var d=!0;a=goog.array.clone(this.eventTargetListeners_[a]);for(var e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.capture==b){var g=f.listener,h=f.handler||f.src;f.callOnce&&this.unlistenByKey(f);d=!1!==g.call(h,c)&&d}}return d&&!1!=c.returnValue_};
goog.events.EventTarget.prototype.getListeners=function(a,b){var c=this.eventTargetListeners_[a],d=[];if(c)for(var e=0;e<c.length;++e){var f=c[e];f.capture==b&&d.push(f)}return d};goog.events.EventTarget.prototype.getListener=function(a,b,c,d){a=this.eventTargetListeners_[a];var e=-1;a&&(e=goog.events.EventTarget.findListenerIndex_(a,b,c,d));return-1<e?a[e]:null};
goog.events.EventTarget.prototype.hasListener=function(a,b){var c=goog.isDef(a),d=goog.isDef(b);return goog.object.some(this.eventTargetListeners_,function(e,f){for(var g=0;g<e.length;++g)if(!(c&&e[g].type!=a||d&&e[g].capture!=b))return!0;return!1})};goog.events.EventTarget.prototype.setTargetForTesting=function(a){this.actualEventTarget_=a};
goog.events.EventTarget.dispatchEventInternal_=function(a,b,c){var d=b.type||b;if(goog.isString(b))b=new goog.events.Event(b,a);else if(b instanceof goog.events.Event)b.target=b.target||a;else{var e=b;b=new goog.events.Event(d,a);goog.object.extend(b,e)}var e=!0,f;if(c)for(var g=c.length-1;!b.propagationStopped_&&0<=g;g--)f=b.currentTarget=c[g],e=f.fireListeners(d,!0,b)&&e;b.propagationStopped_||(f=b.currentTarget=a,e=f.fireListeners(d,!0,b)&&e,b.propagationStopped_||(e=f.fireListeners(d,!1,b)&&e));
if(c)for(g=0;!b.propagationStopped_&&g<c.length;g++)f=b.currentTarget=c[g],e=f.fireListeners(d,!1,b)&&e;return e};goog.events.EventTarget.findListenerIndex_=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(f.listener==b&&f.capture==!!c&&f.handler==d)return e}return-1};/*
 Dual licensed under the MIT or GPL licenses.
*/
pike.events={};pike.events.Update=function(a,b){goog.events.Event.call(this,pike.events.Update.EVENT_TYPE,b);this.now=a};goog.inherits(pike.events.Update,goog.events.Event);pike.events.Update.EVENT_TYPE="update";pike.events.Render=function(a,b){goog.events.Event.call(this,pike.events.Render.EVENT_TYPE,b);this.now=a};goog.inherits(pike.events.Render,goog.events.Event);pike.events.Render.EVENT_TYPE="render";
pike.events.NewEntity=function(a,b){goog.events.Event.call(this,pike.events.NewEntity.EVENT_TYPE,b);this.entity=a};goog.inherits(pike.events.NewEntity,goog.events.Event);pike.events.NewEntity.EVENT_TYPE="newentity";pike.events.RemoveEntity=function(a,b){goog.events.Event.call(this,pike.events.RemoveEntity.EVENT_TYPE,b);this.entity=a};goog.inherits(pike.events.RemoveEntity,goog.events.Event);pike.events.RemoveEntity.EVENT_TYPE="removeentity";
pike.events.Down=function(a,b,c,d){goog.events.Event.call(this,pike.events.Down.EVENT_TYPE,d);this.posX=a;this.posY=b;this.domEvent=c};goog.inherits(pike.events.Down,goog.events.Event);pike.events.Down.EVENT_TYPE="down";pike.events.Up=function(a,b,c,d,e){goog.events.Event.call(this,pike.events.Up.EVENT_TYPE,e);this.posX=a;this.posY=b;this.isMoving=c;this.domEvent=d};goog.inherits(pike.events.Up,goog.events.Event);pike.events.Up.EVENT_TYPE="up";
pike.events.Move=function(a,b,c,d,e,f){goog.events.Event.call(this,pike.events.Move.EVENT_TYPE,f);this.posX=a;this.posY=b;this.deltaX=c;this.deltaY=d;this.domEvent=e};goog.inherits(pike.events.Move,goog.events.Event);pike.events.Move.EVENT_TYPE="move";pike.events.ChangePosition=function(a,b,c,d,e){goog.events.Event.call(this,pike.events.ChangePosition.EVENT_TYPE,e);this.x=a;this.y=b;this.oldX=c;this.oldY=d};goog.inherits(pike.events.ChangePosition,goog.events.Event);
pike.events.ChangePosition.EVENT_TYPE="changeposition";pike.events.ChangeSize=function(a,b,c,d,e){goog.events.Event.call(this,pike.events.ChangeSize.EVENT_TYPE,e);this.w=a;this.h=b;this.oldW=c;this.oldH=d};goog.inherits(pike.events.ChangeSize,goog.events.Event);pike.events.ChangeSize.EVENT_TYPE="changesize";pike.events.Collision=function(a,b,c,d,e,f){goog.events.Event.call(this,pike.events.Collision.EVENT_TYPE,f);this.x=a;this.y=b;this.oldX=c;this.oldY=d;this.obj=e};
goog.inherits(pike.events.Collision,goog.events.Event);pike.events.Collision.EVENT_TYPE="collision";/*
 Dual licensed under the MIT or GPL licenses.
*/
pike.graphics={};pike.graphics.Rectangle=function(a,b,c,d){this.x=a||0;this.y=b||0;this.w=c||0;this.h=d||0};pike.graphics.Rectangle.prototype.copy=function(){return new pike.graphics.Rectangle(this.x,this.y,this.w,this.h)};pike.graphics.Rectangle.prototype.equals=function(a){return this.x==a.x&&this.y==a.y&&this.w==a.w&&this.h==a.h};pike.graphics.Rectangle.prototype.toString=function(){return"[x="+this.x+", y="+this.y+", width="+this.w+", height="+this.h+"]"};
pike.graphics.Rectangle.prototype.intersects=function(a){return this.x<=a.x+a.w&&this.x+this.w>=a.x&&this.y<=a.y+a.h&&this.y+this.h>=a.y};pike.graphics.Rectangle.prototype.intersection=function(a){var b=Math.max(this.x,a.x),c=Math.max(this.y,a.y),d=Math.min(this.x+this.w,a.x+a.w)-b;a=Math.min(this.y+this.h,a.y+a.h)-c;return 0>=d||0>=a?null:new pike.graphics.Rectangle(b,c,d,a)};
pike.graphics.Rectangle.prototype.covers=function(a){return a.x>=this.x&&a.y>=this.y&&a.x+a.w<=this.x+this.w&&a.y+a.h<=this.y+this.h};pike.graphics.Rectangle.prototype.containsPoint=function(a,b){return a>=this.x&&a<this.x+this.w&&b>=this.y&&b<this.y+this.h};pike.graphics.Rectangle.prototype.convexHull=function(a){var b=Math.min(this.x,a.x),c=Math.min(this.y,a.y),d=Math.max(this.x+this.w,a.x+a.w)-b;a=Math.max(this.y+this.h,a.y+a.h)-c;return new pike.graphics.Rectangle(b,c,d,a)};
pike.graphics.Rectangle.prototype.getOverlappingGridCells=function(a,b,c,d){var e=Math.max(0,Math.floor(this.x/a)),f=Math.max(0,Math.floor(this.y/b));a=Math.min(c-e,Math.floor((this.x+this.w)/a)-e+1);b=Math.min(d-f,Math.floor((this.y+this.h)/b)-f+1);return new pike.graphics.Rectangle(e,f,a,b)};pike.graphics.Cluster=function(a,b,c){this.clusterSize_=a;this.bounds_=new pike.graphics.Rectangle(0,0,b,c);this.clusters_=[];this.idToClusterBounds_={}};
pike.graphics.Cluster.prototype.setSize=function(a,b){this.bounds_.w=a;this.bounds_.h=b};pike.graphics.Cluster.prototype.getClusters=function(){return this.clusters_};pike.graphics.Cluster.prototype.getClusterSize=function(){return this.clusterSize_};pike.graphics.Cluster.prototype.getIdToClusterBounds=function(a){return this.idToClusterBounds_[a]};pike.graphics.Cluster.prototype.setIdToClusterBounds=function(a,b){this.idToClusterBounds_[a]=b};
pike.graphics.Cluster.prototype.build=function(){this.clusters_=[];for(var a=0;a<Math.ceil(this.bounds_.h/this.clusterSize_);a++){this.clusters_[a]=[];for(var b=0;b<Math.ceil(this.bounds_.w/this.clusterSize_);b++)this.clusters_[a][b]=[]}};
pike.graphics.Cluster.prototype.addToClusters=function(a,b){b=b||a.getBounds().getOverlappingGridCells(this.clusterSize_,this.clusterSize_,this.clusters_[0].length,this.clusters_.length);for(var c=b.y;c<b.y+b.h;c++)for(var d=b.x;d<b.x+b.w;d++)this.clusters_[c][d].push(a);this.idToClusterBounds_[a.id]=b;goog.DEBUG&&window.console.log("[pike.graphics.Cluster] entity "+a.id+" is added to cluster "+b);return b};
pike.graphics.Cluster.prototype.removeFromClusters=function(a,b){b=b||this.idToClusterBounds_[a.id];for(var c=b.y;c<b.y+b.h;c++)for(var d=b.x;d<b.x+b.w;d++)goog.array.remove(this.clusters_[c][d],a);goog.DEBUG&&window.console.log("[pike.graphics.Cluster] entity "+a.id+" is removed from cluster "+b)};/*
 Dual licensed under the MIT or GPL licenses.
*/
pike.core={};pike.core.Entity=function(a){goog.events.EventTarget.call(this);this.id=goog.getUid(this);this.handler=new goog.events.EventHandler(this);for(var b=0;b<arguments.length;b++){if("function"!==typeof arguments[b])throw"Argument is not a function "+arguments[b];arguments[b].call(this)}};goog.inherits(pike.core.Entity,goog.events.EventTarget);pike.core.Entity.prototype.getBounds=function(){return new pike.graphics.Rectangle(this.x,this.y,this.w,this.h)};
pike.core.Entity.prototype.disposeInternal=function(){pike.core.Entity.superClass_.disposeInternal.call(this);this.handler.dispose()};pike.core.Viewport=function(){goog.events.EventTarget.call(this);this.viewport_=new pike.graphics.Rectangle(0,0,0,0);this.handler=new goog.events.EventHandler(this)};goog.inherits(pike.core.Viewport,goog.events.EventTarget);
pike.core.Viewport.prototype.setSize=function(a,b){var c=this.viewport_.w,d=this.viewport_.h;this.viewport_.w=a;this.viewport_.h=b;goog.DEBUG&&window.console.log("[pike.core.Viewport] changesize");this.dispatchEvent(new pike.events.ChangeSize(this.viewport_.w,this.viewport_.h,c,d,this))};
pike.core.Viewport.prototype.setPosition=function(a,b){var c=this.viewport_.x,d=this.viewport_.y;this.viewport_.x=a;this.viewport_.y=b;goog.DEBUG&&window.console.log("[pike.core.Viewport] changeposition");this.dispatchEvent(new pike.events.ChangePosition(this.viewport_.x,this.viewport_.y,c,d,this))};pike.core.Viewport.prototype.getBounds=function(){return this.viewport_.copy()};
pike.core.GameWorld=function(){goog.events.EventTarget.call(this);this.bounds_=new pike.graphics.Rectangle(0,0,0,0);this.handler=new goog.events.EventHandler(this)};goog.inherits(pike.core.GameWorld,goog.events.EventTarget);pike.core.GameWorld.prototype.setSize=function(a,b){var c=this.bounds_.w,d=this.bounds_.h;this.bounds_.w=a;this.bounds_.h=b;goog.DEBUG&&window.console.log("[pike.core.GameWorld] changesize");this.dispatchEvent(new pike.events.ChangeSize(this.bounds_.w,this.bounds_.h,c,d,this))};
pike.core.GameWorld.prototype.getBounds=function(){return this.bounds_.copy()};pike.core.Timer=function(){goog.events.EventTarget.call(this);this.handler=new goog.events.EventHandler(this);this.boundTick_=goog.bind(this.tick,this)};goog.inherits(pike.core.Timer,goog.events.EventTarget);pike.core.Timer.prototype.start=function(){this.stop();this.tick()};pike.core.Timer.prototype.stop=function(){this.requestID_&&window.cancelAnimationFrame(this.requestID_)};
pike.core.Timer.prototype.tick=function(){this.dispatchEvent(new pike.events.Update((new Date).getTime(),this));this.dispatchEvent(new pike.events.Render((new Date).getTime(),this));this.requestID_=window.requestAnimationFrame(this.boundTick_)};pike.core.Stage=function(){goog.events.EventTarget.call(this);this.viewport_=new pike.graphics.Rectangle(0,0,0,0);this.gameWorld_=new pike.graphics.Rectangle(0,0,0,0);this.layers_=[];this.createRootElement_();this.handler=new goog.events.EventHandler(this)};
goog.inherits(pike.core.Stage,goog.events.EventTarget);pike.core.Stage.ELEMENT_ID="pike-stage";pike.core.Stage.prototype.getLayer=function(a){for(var b=0;b<this.layers_.length;b++)if(this.layers_[b].name==a)return this.layers_[b];throw Error("Layer with name "+a+" does not exist.");};pike.core.Stage.prototype.addLayer=function(a){this.setLayerSize_(a);this.layers_.push(a);this.getRootElement().appendChild(a.getScreen().canvas)};pike.core.Stage.prototype.getRootElement=function(){return this.rootElement_};
pike.core.Stage.prototype.onRender=function(a){for(a=0;a<this.layers_.length;a++)this.layers_[a].onRender()};pike.core.Stage.prototype.onViewportChangeSize=function(a){this.setViewportSize_(a.w,a.h)};pike.core.Stage.prototype.onViewportChangePosition=function(a){this.setViewportPosition_(a.x,a.y)};pike.core.Stage.prototype.onGameWorldChangeSize=function(a){this.setGameWorldSize_(a.w,a.h)};
pike.core.Stage.prototype.createRootElement_=function(){(this.rootElement_=document.getElementById(pike.core.Stage.ELEMENT_ID))?this.rootElement_.innerHTML="":(this.rootElement_=document.createElement("div"),this.rootElement_.setAttribute("id",pike.core.Stage.ELEMENT_ID),document.getElementsByTagName("body")[0].appendChild(this.rootElement_));this.rootElement_.style.position="relative"};
pike.core.Stage.prototype.setLayerSize_=function(a){a.setViewportSize(this.viewport_.w,this.viewport_.h);a.setViewportPosition(this.viewport_.x,this.viewport_.y);a.setGameWorldSize(this.gameWorld_.w,this.gameWorld_.h)};
pike.core.Stage.prototype.setViewportSize_=function(a,b){if(this.viewport_.w!=a||this.viewport_.h!=b){this.viewport_.w=a;this.viewport_.h=b;this.rootElement_.style.width=this.viewport_.w+"px";this.rootElement_.style.height=this.viewport_.h+"px";(this.gameWorld_.w<a||this.gameWorld_.h<b)&&this.setGameWorldSize_(a,b);for(var c=0;c<this.layers_.length;c++)this.setLayerSize_(this.layers_[c])}};
pike.core.Stage.prototype.setGameWorldSize_=function(a,b){this.gameWorld_.w=Math.max(a,this.viewport_.w);this.gameWorld_.h=Math.max(b,this.viewport_.h);for(var c=0;c<this.layers_.length;c++)this.setLayerSize_(this.layers_[c])};pike.core.Stage.prototype.setViewportPosition_=function(a,b){this.viewport_.x=a;this.viewport_.y=b;for(var c=0;c<this.layers_.length;c++)this.layers_[c].setViewportPosition(this.viewport_.x,this.viewport_.y)};/*
 Dual licensed under the MIT or GPL licenses.
*/
pike.input={};pike.input.InputHandlerBase=function(){goog.events.EventTarget.call(this);this.handler=new goog.events.EventHandler(this);this.viewport_=new pike.graphics.Rectangle(0,0,0,0);this.element_=null;this.moving_=!1;this.lastMoveCoordinates_=null;this.moveThreshold_=10;this.stopDomEvents_=!0};goog.inherits(pike.input.InputHandlerBase,goog.events.EventTarget);
pike.input.InputHandlerBase.prototype.onDownDomEvent=function(a){var b=this.lastMoveCoordinates_=this.getInputCoordinates_(a);goog.DEBUG&&window.console.log("[pike.core.InputHanderBase] down "+b.posX+", "+b.posY);this.dispatchEvent(new pike.events.Down(b.posX,b.posY,a,this));this.stopEventIfRequired_(a)};
pike.input.InputHandlerBase.prototype.onUpDomEvent=function(a){var b=this.getInputCoordinates_(a);goog.DEBUG&&window.console.log("[pike.core.InputHanderBase] up "+b.posX+", "+b.posY+", moving: "+this.moving_);this.dispatchEvent(new pike.events.Up(b.posX,b.posY,this.moving_,a,this));this.stopEventIfRequired_(a);this.moving_=!1};
pike.input.InputHandlerBase.prototype.onMoveDomEvent=function(a){var b=this.getInputCoordinates_(a),c=b.posX-this.lastMoveCoordinates_.posX,d=b.posY-this.lastMoveCoordinates_.posY;!this.moving_&&Math.sqrt(c*c+d*d)>this.moveThreshold_&&(this.moving_=!0);this.moving_&&(goog.DEBUG&&window.console.log("[pike.core.InputHanderBase] move "+b.posX+", "+b.posY+", deltaX: "+c+", deltaY: "+d),this.dispatchEvent(new pike.events.Move(b.posX,b.posY,c,d,a,this)),this.lastMoveCoordinates_=b);this.stopEventIfRequired_(a)};
pike.input.InputHandlerBase.prototype.stopEventIfRequired_=function(a){this.stopDomEvents_&&(a.stopPropagation(),a.preventDefault())};pike.input.InputHandlerBase.prototype.getInputCoordinates_=function(a){return{posX:a.offsetX+this.viewport_.x,posY:a.offsetY+this.viewport_.y}};pike.input.InputHandlerBase.prototype.onViewportChangePosition=function(a){this.viewport_.x=a.x;this.viewport_.y=a.y};pike.input.MouseInputHandler=function(){pike.input.InputHandlerBase.call(this);this.mouseDown_=!1};
goog.inherits(pike.input.MouseInputHandler,pike.input.InputHandlerBase);pike.input.MouseInputHandler.prototype.setEventTarget=function(a){this.element_=a;this.attachDomListeners_()};
pike.input.MouseInputHandler.prototype.attachDomListeners_=function(){var a=this.element_;this.handler.listen(a,goog.events.EventType.MOUSEDOWN,goog.bind(this.onDownDomEvent,this));this.handler.listen(a,goog.events.EventType.MOUSEUP,goog.bind(this.onUpDomEvent,this));this.handler.listen(a,goog.events.EventType.MOUSEMOVE,goog.bind(this.onMoveDomEvent,this));this.handler.listen(a,goog.events.EventType.MOUSEOUT,goog.bind(this.onMouseOut,this))};
pike.input.MouseInputHandler.prototype.onDownDomEvent=function(a){this.mouseDown_=!0;pike.input.InputHandlerBase.prototype.onDownDomEvent.call(this,a)};pike.input.MouseInputHandler.prototype.onUpDomEvent=function(a){this.mouseDown_=!1;pike.input.InputHandlerBase.prototype.onUpDomEvent.call(this,a)};pike.input.MouseInputHandler.prototype.onMoveDomEvent=function(a){this.mouseDown_&&pike.input.InputHandlerBase.prototype.onMoveDomEvent.call(this,a)};
pike.input.MouseInputHandler.prototype.onMouseOut=function(){this.mouseDown_=!1};pike.input.TouchInputHandler=function(){pike.input.InputHandlerBase.call(this);this.lastInteractionCoordinates_=null};goog.inherits(pike.input.TouchInputHandler,pike.input.InputHandlerBase);pike.input.TouchInputHandler.prototype.setEventTarget=function(a){this.element_=a;this.attachDomListeners_()};
pike.input.TouchInputHandler.prototype.attachDomListeners_=function(){var a=this.element_;this.handler.listen(a,goog.events.EventType.TOUCHSTART,goog.bind(this.onDownDomEvent,this));this.handler.listen(a,goog.events.EventType.TOUCHEND,goog.bind(this.onUpDomEvent,this));this.handler.listen(a,goog.events.EventType.TOUCHMOVE,goog.bind(this.onMoveDomEvent,this))};
pike.input.TouchInputHandler.prototype.onDownDomEvent=function(a){this.lastInteractionCoordinates_=this.getInputCoordinates_(a);pike.input.InputHandlerBase.prototype.onDownDomEvent.call(this,a)};
pike.input.TouchInputHandler.prototype.onUpDomEvent=function(a){goog.DEBUG&&window.console.log("[pike.core.TouchHanderBase] up "+this.lastInteractionCoordinates_.posX+", "+this.lastInteractionCoordinates_.posY+", moving: "+this.moving_);this.dispatchEvent(new pike.events.Up(this.lastInteractionCoordinates_.posX,this.lastInteractionCoordinates_.posY,this.moving_,a,this));this.stopEventIfRequired_(a);this.lastInteractionCoordinates_=null;this.moving_=!1};
pike.input.TouchInputHandler.prototype.onMoveDomEvent=function(a){this.lastInteractionCoordinates_=this.getInputCoordinates_(a);pike.input.InputHandlerBase.prototype.onMoveDomEvent.call(this,a)};goog.events.EventHandler=function(a){goog.Disposable.call(this);this.handler_=a;this.keys_={}};goog.inherits(goog.events.EventHandler,goog.Disposable);goog.events.EventHandler.typeArray_=[];goog.events.EventHandler.prototype.listen=function(a,b,c,d,e){goog.isArray(b)||(goog.events.EventHandler.typeArray_[0]=b,b=goog.events.EventHandler.typeArray_);for(var f=0;f<b.length;f++){var g=goog.events.listen(a,b[f],c||this,d||!1,e||this.handler_||this);if(goog.DEBUG&&!g)break;this.keys_[g.key]=g}return this};
goog.events.EventHandler.prototype.listenOnce=function(a,b,c,d,e){if(goog.isArray(b))for(var f=0;f<b.length;f++)this.listenOnce(a,b[f],c,d,e);else a=goog.events.listenOnce(a,b,c||this,d,e||this.handler_||this),this.keys_[a.key]=a;return this};goog.events.EventHandler.prototype.listenWithWrapper=function(a,b,c,d,e){b.listen(a,c,d,e||this.handler_||this,this);return this};
goog.events.EventHandler.prototype.getListenerCount=function(){var a=0,b;for(b in this.keys_)Object.prototype.hasOwnProperty.call(this.keys_,b)&&a++;return a};goog.events.EventHandler.prototype.unlisten=function(a,b,c,d,e){if(goog.isArray(b))for(var f=0;f<b.length;f++)this.unlisten(a,b[f],c,d,e);else if(a=goog.events.getListener(a,b,c||this,d,e||this.handler_||this))goog.events.unlistenByKey(a),delete this.keys_[a.key];return this};
goog.events.EventHandler.prototype.unlistenWithWrapper=function(a,b,c,d,e){b.unlisten(a,c,d,e||this.handler_||this,this);return this};goog.events.EventHandler.prototype.removeAll=function(){goog.object.forEach(this.keys_,goog.events.unlistenByKey);this.keys_={}};goog.events.EventHandler.prototype.disposeInternal=function(){goog.events.EventHandler.superClass_.disposeInternal.call(this);this.removeAll()};
goog.events.EventHandler.prototype.handleEvent=function(a){throw Error("EventHandler.handleEvent not implemented");};/*
 Dual licensed under the MIT or GPL licenses.
*/
pike.layers={};
pike.layers.Layer=function(a){goog.events.EventTarget.call(this);this.name=a;this.handler=new goog.events.EventHandler(this);this.viewport_=new pike.graphics.Rectangle(0,0,0,0);this.gameWorld_=new pike.graphics.Rectangle(0,0,0,0);this.entities_=[];this.screen_={};this.offScreen_={};this.screen_.canvas=document.createElement("canvas");this.screen_.canvas.style.position="absolute";this.screen_.canvas.style.top="0";this.screen_.canvas.style.left="0";this.screen_.context=this.screen_.canvas.getContext("2d");this.screen_.isDirty=
!1;this.offScreen_.canvas=document.createElement("canvas");this.offScreen_.context=this.offScreen_.canvas.getContext("2d");this.offScreen_.isDirty=!1};goog.inherits(pike.layers.Layer,goog.events.EventTarget);pike.layers.Layer.prototype.onRender=function(){this.hasDirtyManager()?this.renderDirty_():this.offScreen_.isDirty&&this.renderOffScreen_();this.screen_.isDirty&&this.renderScreen_()};
pike.layers.Layer.prototype.renderDirty_=function(){this.dirtyManager.isClean()||(this.offScreen_.context.clearRect(this.dirtyManager.getDirtyRectangle().x,this.dirtyManager.getDirtyRectangle().y,this.dirtyManager.getDirtyRectangle().w,this.dirtyManager.getDirtyRectangle().h),this.dispatchEvent(new pike.events.Render((new Date).getTime(),this)),this.screen_.isDirty||(this.screen_.context.clearRect(this.dirtyManager.getDirtyRectangle().x-this.viewport_.x,this.dirtyManager.getDirtyRectangle().y-this.viewport_.y,
this.dirtyManager.getDirtyRectangle().w,this.dirtyManager.getDirtyRectangle().h),this.screen_.context.drawImage(this.offScreen_.canvas,this.dirtyManager.getDirtyRectangle().x,this.dirtyManager.getDirtyRectangle().y,this.dirtyManager.getDirtyRectangle().w,this.dirtyManager.getDirtyRectangle().h,this.dirtyManager.getDirtyRectangle().x-this.viewport_.x,this.dirtyManager.getDirtyRectangle().y-this.viewport_.y,this.dirtyManager.getDirtyRectangle().w,this.dirtyManager.getDirtyRectangle().h)),this.dirtyManager.clear())};
pike.layers.Layer.prototype.renderOffScreen_=function(){this.offScreen_.context.clearRect(0,0,this.gameWorld_.w,this.gameWorld_.h);this.dispatchEvent(new pike.events.Render((new Date).getTime(),this));this.offScreen_.isDirty=!1;this.screen_.isDirty=!0;goog.DEBUG&&window.console.log("[pike.core.Layer] "+this.name+" redraw offScreen")};
pike.layers.Layer.prototype.renderScreen_=function(){this.screen_.context.clearRect(0,0,this.viewport_.w,this.viewport_.h);this.screen_.context.drawImage(this.offScreen_.canvas,this.viewport_.x,this.viewport_.y,this.viewport_.w,this.viewport_.h,0,0,this.viewport_.w,this.viewport_.h);this.screen_.isDirty=!1;goog.DEBUG&&window.console.log("[pike.core.Layer] "+this.name+" redraw screen")};
pike.layers.Layer.prototype.setViewportSize=function(a,b){this.viewport_.w=a;this.viewport_.h=b;this.screen_.canvas.width=this.viewport_.w;this.screen_.canvas.height=this.viewport_.h;this.screen_.isDirty=!0;this.hasDirtyManager()&&this.dirtyManager.setSize(this.viewport_.w,this.viewport_.h)};
pike.layers.Layer.prototype.setGameWorldSize=function(a,b){this.gameWorld_.w=a;this.gameWorld_.h=b;this.offScreen_.canvas.width=this.gameWorld_.w;this.offScreen_.canvas.height=this.gameWorld_.h;this.offScreen_.isDirty=!0};pike.layers.Layer.prototype.setViewportPosition=function(a,b){this.viewport_.x=a;this.viewport_.y=b;this.getScreen().isDirty=!0;this.hasDirtyManager()&&this.dirtyManager.setPosition(this.viewport_.x,this.viewport_.y)};
pike.layers.Layer.prototype.setDirtyManager=function(a){this.dirtyManager=a};pike.layers.Layer.prototype.hasDirtyManager=function(){return this.dirtyManager};pike.layers.Layer.prototype.getScreen=function(){return this.screen_};pike.layers.Layer.prototype.getOffScreen=function(){return this.offScreen_};
pike.layers.Layer.prototype.addEntity=function(a){this.entities_.push(a);a.layer=this;this.dispatchEvent(new pike.events.NewEntity(a,this));goog.DEBUG&&window.console.log("[pike.core.Layer] Layer: "+this.name+" has newentity #"+a.id)};pike.layers.Layer.prototype.removeEntity=function(a){a.dispose();goog.array.remove(this.entities_,a);delete a.layer;this.dispatchEvent(new pike.events.RemoveEntity(a,this));goog.DEBUG&&window.console.log("[pike.core.Layer] removeentity")};
pike.layers.Layer.prototype.dispatchEvent=function(a){for(var b=0;b<this.entities_.length;b++)this.entities_[b].dispatchEvent(a);goog.events.EventTarget.prototype.dispatchEvent.call(this,a)};pike.layers.ClusterLayer=function(a,b){pike.layers.Layer.call(this,a);this.clusters_=new pike.graphics.Cluster(b,0,0);this.visibleClusterBounds_={};this.cache_=[];this.cacheDirty_=!0;this.cacheUnsorted_=!1};goog.inherits(pike.layers.ClusterLayer,pike.layers.Layer);
pike.layers.ClusterLayer.prototype.getCluster=function(){return this.clusters_};pike.layers.ClusterLayer.prototype.dispatchEvent=function(a){this.cacheDirty_?this.resetCache_():this.cacheUnsorted_&&this.sortCache_();for(var b=0;b<this.cache_.length;b++){var c=this.cache_[b];c.getBounds().intersects(this.viewport_)&&c.dispatchEvent(a)}goog.events.EventTarget.prototype.dispatchEvent.call(this,a)};
pike.layers.ClusterLayer.prototype.addEntity=function(a){pike.layers.Layer.prototype.addEntity.call(this,a);this.handler.listen(a,pike.events.ChangePosition.EVENT_TYPE,goog.bind(this.onEntityMove,this));0!=this.clusters_.getClusters().length&&this.clusters_.addToClusters(a).intersects(this.visibleClusterBounds_)&&(this.cache_.push(a),this.cacheUnsorted_=!0)};
pike.layers.ClusterLayer.prototype.removeEntity=function(a){this.clusters_.removeFromClusters(a);pike.layers.Layer.prototype.removeEntity.call(this,a)};
pike.layers.ClusterLayer.prototype.resetCache_=function(){for(var a=this.cache_=[],b=this.visibleClusterBounds_.y;b<this.visibleClusterBounds_.y+this.visibleClusterBounds_.h;b++)for(var c=this.visibleClusterBounds_.x;c<this.visibleClusterBounds_.x+this.visibleClusterBounds_.w;c++)for(var d=this.clusters_.getClusters()[b][c],e=0;e<d.length;e++)-1==a.indexOf(d[e])&&a.push(d[e]);goog.DEBUG&&window.console.log("[pike.layers.ClusterLayer] resetcache");this.sortCache_();this.cacheUnsorted_=this.cacheDirty_=
!1};pike.layers.ClusterLayer.prototype.sortCache_=function(){this.cache_.sort(function(a,b){var c=a.getBounds(),d=b.getBounds();return c.y+c.h-(d.y+d.h)});this.cacheUnsorted_=!1;goog.DEBUG&&window.console.log("[pike.layers.ClusterLayer] sortcache")};pike.layers.ClusterLayer.prototype.resetClusters_=function(){this.clusters_.build();goog.DEBUG&&window.console.log("[pike.layers.ClusterLayer] resetcluster");for(var a=0;a<this.entities_.length;a++)this.clusters_.addToClusters(this.entities_[a])};
pike.layers.ClusterLayer.prototype.updateVisibleClusters_=function(){var a=this.viewport_.getOverlappingGridCells(this.clusters_.getClusterSize(),this.clusters_.getClusterSize(),this.clusters_.getClusters()[0].length,this.clusters_.getClusters().length);a.equals(this.visibleClusterBounds_)||(this.visibleClusterBounds_=a,this.cacheDirty_=!0)};
pike.layers.ClusterLayer.prototype.setViewportSize=function(a,b){pike.layers.Layer.prototype.setViewportSize.call(this,a,b);this.setGameWorldSize.call(this,Math.max(this.gameWorld_.w,a),Math.max(this.gameWorld_.h,b));this.updateVisibleClusters_()};pike.layers.ClusterLayer.prototype.setViewportPosition=function(a,b){pike.layers.Layer.prototype.setViewportPosition.call(this,a,b);this.updateVisibleClusters_()};
pike.layers.ClusterLayer.prototype.setGameWorldSize=function(a,b){pike.layers.Layer.prototype.setGameWorldSize.call(this,a,b);this.clusters_.setSize(a,b);this.resetClusters_()};
pike.layers.ClusterLayer.prototype.onEntityMove=function(a){var b=a.target,c=b.getBounds().getOverlappingGridCells(this.clusters_.getClusterSize(),this.clusters_.getClusterSize(),this.clusters_.getClusters()[0].length,this.clusters_.getClusters().length),d=this.clusters_.getIdToClusterBounds(b.id);d.equals(c)||this.moveObjectBetweenClusters_(b,d,c);c.intersects(this.visibleClusterBounds_)&&a.y!=a.oldY&&(this.cacheUnsorted_=!0)};
pike.layers.ClusterLayer.prototype.moveObjectBetweenClusters_=function(a,b,c){this.clusters_.removeFromClusters(a,b);this.clusters_.addToClusters(a,c);this.clusters_.setIdToClusterBounds(a.id,c);c.intersects(this.visibleClusterBounds_)?goog.array.contains(this.cache_,a)||this.cache_.push(a):goog.array.remove(this.cache_,a)};pike.layers.ObstacleLayer=function(a){pike.layers.Layer.call(this,a)};goog.inherits(pike.layers.ObstacleLayer,pike.layers.Layer);
pike.layers.ObstacleLayer.prototype.setViewportSize=function(a,b){pike.layers.Layer.prototype.setViewportSize.call(this,a,b);this.screen_.isDirty=!1};pike.layers.ObstacleLayer.prototype.setViewportPosition=function(a,b){pike.layers.Layer.prototype.setViewportPosition.call(this,a,b);this.screen_.isDirty=!1};
pike.layers.ObstacleLayer.prototype.renderOffScreen_=function(){pike.layers.Layer.prototype.renderOffScreen_.call(this);this.screen_.isDirty=!1;goog.DEBUG&&window.console.log("[pike.core.ObstacleLayer] "+this.name+" redraw offScreen")};
pike.layers.ObstacleLayer.prototype.onEntityChangePosition=function(a){var b=a.target,b=b.getCollisionBounds()||b.getBounds();0==this.offScreen_.context.getImageData(b.x,b.y,1,1).data[3]&&0==this.offScreen_.context.getImageData(b.x+b.w,b.y,1,1).data[3]&&0==this.offScreen_.context.getImageData(b.x+b.w,b.y+b.h,1,1).data[3]&&0==this.offScreen_.context.getImageData(b.x,b.y+b.h,1,1).data[3]||a.target.dispatchEvent(new pike.events.Collision(a.x,a.y,a.oldX,a.oldY,"obstacle",a.target))};
pike.layers.DirtyManager=function(a){this.viewport_=new pike.graphics.Rectangle(0,0,0,0);this.handler=new goog.events.EventHandler(this);this.dirtyRect_=null;this.allDirtyThreshold_=void 0==a?0.5:a;this.allDirty_=!0;this.markAllDirty()};pike.layers.DirtyManager.prototype.getDirtyRectangle=function(){return this.dirtyRect_};pike.layers.DirtyManager.prototype.markAllDirty=function(){this.allDirty_=!0;this.dirtyRect_=this.viewport_.copy()};
pike.layers.DirtyManager.prototype.markDirty=function(a){(a.w||a.h)&&!this.allDirty_&&(a=this.viewport_.intersection(a))&&(this.dirtyRect_=this.dirtyRect_?this.dirtyRect_.convexHull(a):a,this.dirtyRect_.w*this.dirtyRect_.h>this.allDirtyThreshold_*this.viewport_.w*this.viewport_.h&&this.markAllDirty())};pike.layers.DirtyManager.prototype.isClean=function(){return!this.dirtyRect_};pike.layers.DirtyManager.prototype.clear=function(){this.dirtyRect_=null;this.allDirty_=!1};
pike.layers.DirtyManager.prototype.setSize=function(a,b){this.viewport_.w=a;this.viewport_.h=b;this.markAllDirty()};pike.layers.DirtyManager.prototype.setPosition=function(a,b){this.viewport_.x=a;this.viewport_.y=b};/*
 Dual licensed under the MIT or GPL licenses.
*/
pike.components={};
pike.components.Collision=function(){this.setCollisionBounds=function(a,b,c,d){this.collisionBounds_=new pike.graphics.Rectangle(a,b,c,d);return this};this.checkCollision=function(a){for(var b=this.layer.getCluster().getIdToClusterBounds(this.id),b=this.layer.getCluster().getClusters()[b.y][b.x],c=0;c<b.length;c++)this.id!=b[c].id&&this.getCollisionBounds(this).intersects(b[c].getCollisionBounds()||b[c].getBounds())&&this.dispatchEvent(new pike.events.Collision(a.x,a.y,a.oldX,a.oldY,b[c],this))};
this.getCollisionBounds=function(){return new pike.graphics.Rectangle(this.x+this.collisionBounds_.x,this.y+this.collisionBounds_.y,this.w-this.collisionBounds_.w,this.h-this.collisionBounds_.h)};this.handler.listen(this,pike.events.ChangePosition.EVENT_TYPE,goog.bind(this.checkCollision,this))};
pike.components.Sprite=function(){this.y=this.x=100;this.h=this.w=32;this.spriteSource={};this.setSprite=function(a,b,c,d,e,f,g){this.spriteSource.image=a;this.spriteSource.x=b;this.spriteSource.y=c;this.spriteSource.w=d;this.spriteSource.h=e;this.spriteSource.row=0;this.spriteSource.numberOfFrames=f||1;this.spriteSource.currentFrame=0;this.spriteSource.animator=new pike.animation.Animator(g||1E3);this.spriteSource.animator.start();this.spriteSource.lastUpdate=(new Date).getTime();return this};this.onSpriteUpdate=
function(a){a=a.now;var b=a-this.spriteSource.lastUpdate;this.spriteSource.lastUpdate=a;a=this.spriteSource.animator.update(b);this.spriteSource.currentFrame=Math.floor(a*this.spriteSource.numberOfFrames);this.setDirty(this.getBounds())};this.setSpriteRow=function(a,b){Math.abs(a)>Math.abs(b)?0<=a?this.spriteSource.row=pike.components.Sprite.RIGHT:this.spriteSource.row=pike.components.Sprite.LEFT:0<=b?this.spriteSource.row=pike.components.Sprite.DOWN:this.spriteSource.row=pike.components.Sprite.UP};
this.onSpriteRender=function(a){this.layer.getOffScreen().context.drawImage(this.spriteSource.image,this.spriteSource.x+this.spriteSource.currentFrame*this.spriteSource.w,this.spriteSource.y+this.spriteSource.row*this.spriteSource.h,this.spriteSource.w,this.spriteSource.h,this.x,this.y,this.w,this.h)};this.setDirty=function(a){this.layer.hasDirtyManager()?this.layer.dirtyManager.markDirty(a):this.layer.getOffScreen().isDirty=!0}};pike.components.Sprite.DOWN=0;pike.components.Sprite.LEFT=1;
pike.components.Sprite.RIGHT=2;pike.components.Sprite.UP=3;pike.components.Image=function(){this.h=this.w=this.y=this.x=0;this.setImage=function(a){this.image=a;this.w=a.width;this.h=a.height};this.onImageRender=function(a){this.layer.getOffScreen().context.drawImage(this.image,0,0,this.w,this.h,0,0,this.w,this.h)}};
pike.components.Watch=function(){this.watchMe=function(a,b){var c=a.getBounds(),d=b.getBounds(),e=c.x,f=c.y;this.x<this.leftInnerBoundary(c)&&(c.x=Math.max(0,Math.min(Math.floor(this.x-0.25*c.w),d.w-c.w)));this.x+this.w>this.rightInnerBoundary(c)&&(c.x=Math.max(0,Math.min(Math.floor(this.x+this.w-0.75*c.w),d.w-c.w)));this.y<this.topInnerBoundary(c)&&(c.y=Math.max(0,Math.min(Math.floor(this.y-0.25*c.h),d.h-c.h)));this.y+this.h>this.bottomInnerBoundary(c)&&(c.y=Math.max(0,Math.min(Math.floor(this.y+
this.h-0.75*c.h),d.h-c.h)));e==c.x&&f==c.y||a.setPosition(c.x,c.y)};this.rightInnerBoundary=function(a){return a.x+0.75*a.w};this.leftInnerBoundary=function(a){return a.x+0.25*a.w};this.topInnerBoundary=function(a){return a.y+0.25*a.h};this.bottomInnerBoundary=function(a){return a.y+0.75*a.h}};/*
 Dual licensed under the MIT or GPL licenses.
*/
pike.assets={};pike.assets.ImageManager=function(){this.images_={}};pike.assets.ImageManager.prototype.load=function(a,b,c){var d=[],e;for(e in a)d.push({key:e,path:a[e]});if(0==d.length)c&&c(0,0,null,null,!0),b&&b();else for(a={loaded:0,total:d.length},e=0;e<d.length;e++)this.loadImage_(d[e],a,b,c)};pike.assets.ImageManager.prototype.get=function(a){return this.images_[a]};
pike.assets.ImageManager.prototype.loadImage_=function(a,b,c,d){var e=this,f=new Image;f.onload=function(){e.images_[a.key]=f;e.onItemLoaded_(a,b,c,d,!0)};f.onerror=function(){e.onItemLoaded_(a,b,c,d,!1)};f.src=a.path};pike.assets.ImageManager.prototype.onItemLoaded_=function(a,b,c,d,e){b.loaded++;d&&d(b.loaded,b.total,a.key,a.path,e);b.loaded==b.total&&c&&c()};
