// This file was autogenerated by calcdeps.py
goog.addDependency("../../../Pike/source/gameworld.js", ['pike.core.Gameworld'], ['pike.graphics.Rectangle', 'pike.events.GameworldChangeSize', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler']);
goog.addDependency("../../../Pike/source/timer.js", ['pike.core.Timer'], ['goog.events.EventTarget', 'goog.events.EventHandler', 'pike.events.Update', 'pike.events.Render']);
goog.addDependency("../../../Pike/source/render_manager.js", ['pike.core.RenderManager'], ['pike.graphics.Rectangle', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler', 'goog.array']);
goog.addDependency("../../../Pike/source/events.js", ['pike.events.ViewportChangePosition', 'pike.events.ViewportChangeSize', 'pike.events.Update', 'pike.events.Render', 'pike.events.NewEntity', 'pike.events.RemoveEntity', 'pike.events.GameworldChangeSize'], ['goog.events.Event', 'goog.events.EventTarget']);
goog.addDependency("../../../Pike/source/viewport.js", ['pike.core.Viewport'], ['pike.graphics.Rectangle', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler']);
goog.addDependency("../../../Pike/source/rectangle.js", ['pike.graphics.Rectangle'], []);
goog.addDependency("../../../Pike/source/entity_manager.js", ['pike.core.EntityManager', 'pike.core.Entity'], ['pike.graphics.Rectangle', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler', 'goog.array']);
