// This file was autogenerated by calcdeps.py
goog.addDependency("../../../Pike/source/events.js", ['pike.events.ViewportChangePosition', 'pike.events.ViewportChangeSize'], ['goog.events.Event']);
goog.addDependency("../../../Pike/source/viewport.js", ['pike.core.Viewport'], ['pike.graphics.Rectangle', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler']);
goog.addDependency("../../../Pike/source/rectangle.js", ['pike.graphics.Rectangle'], []);
