// This file was autogenerated by calcdeps.py
goog.addDependency("../../../Pike/source/components.js", ['pike.components.Sprite'], ['goog.events.EventHandler']);
goog.addDependency("../../../Pike/source/deps.js", [], []);
goog.addDependency("../../../Pike/source/input_handler.js", ['pike.input.InputHandlerBase', 'pike.input.MouseInputHandler', 'pike.input.TouchInputHandler'], ['pike.graphics.Rectangle', 'pike.events.Down', 'pike.events.Up', 'pike.events.Move']);
goog.addDependency("../../../Pike/source/rectangle.js", ['pike.graphics.Rectangle'], []);
goog.addDependency("../../../Pike/source/stage.js", ['pike.core.Stage'], ['pike.graphics.Rectangle', 'pike.events.ViewportChangePosition', 'pike.events.ViewportChangeSize', 'pike.events.GameWorldChangeSize', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler', 'goog.array']);
goog.addDependency("../../../Pike/source/assets.js", ['pike.assets.ImageManager'], []);
goog.addDependency("../../../Pike/source/entity.js", ['pike.core.Entity'], ['pike.graphics.Rectangle', 'goog.events.EventTarget', 'goog.events.EventHandler']);
goog.addDependency("../../../Pike/source/timer.js", ['pike.core.Timer'], ['goog.events.EventTarget', 'goog.events.EventHandler', 'pike.events.Update', 'pike.events.Render']);
goog.addDependency("../../../Pike/source/dirty_manager.js", ['pike.layers.DirtyManager'], ['goog.events.EventTarget', 'pike.graphics.Rectangle']);
goog.addDependency("../../../Pike/source/layers.js", ['pike.layers.Layer'], ['goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler', 'pike.events.NewEntity', 'pike.events.RemoveEntity', 'pike.core.Entity']);
goog.addDependency("../../../Pike/source/events.js", ['pike.events.ViewportChangePosition', 'pike.events.ViewportChangeSize', 'pike.events.GameWorldChangeSize', 'pike.events.Update', 'pike.events.Render', 'pike.events.NewEntity', 'pike.events.RemoveEntity', 'pike.events.Down', 'pike.events.Up', 'pike.events.Move'], ['goog.events.Event', 'goog.events.EventTarget']);
