// This file was autogenerated by calcdeps.py
goog.addDependency("../../../Pike/source/components.js", ['pike.components.Sprite'], ['goog.events.EventHandler']);
goog.addDependency("../../../Pike/source/deps.js", [], []);
goog.addDependency("../../../Pike/source/render_manager.js", ['pike.core.RenderManager'], ['pike.graphics.Rectangle', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler', 'goog.array']);
goog.addDependency("../../../Pike/source/viewport.js", ['pike.core.Viewport'], ['pike.graphics.Rectangle', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler']);
goog.addDependency("../../../Pike/source/rectangle.js", ['pike.graphics.Rectangle'], []);
goog.addDependency("../../../Pike/source/assets.js", ['pike.assets.ImageManager'], []);
goog.addDependency("../../../Pike/source/entity.js", ['pike.core.Entity'], ['pike.graphics.Rectangle', 'goog.events.EventTarget', 'goog.events.EventHandler']);
goog.addDependency("../../../Pike/source/timer.js", ['pike.core.Timer'], ['goog.events.EventTarget', 'goog.events.EventHandler', 'pike.events.Update', 'pike.events.Render']);
goog.addDependency("../../../Pike/source/dirty_manager.js", ['pike.layers.DirtyManager'], ['goog.events.EventTarget']);
goog.addDependency("../../../Pike/source/game_world.js", ['pike.core.GameWorld'], ['pike.graphics.Rectangle', 'pike.events.ChangeSize', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler']);
goog.addDependency("../../../Pike/source/layers.js", ['pike.layers.Layer'], ['goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler', 'pike.events.NewEntity', 'pike.events.RemoveEntity', 'pike.core.Entity']);
goog.addDependency("../../../Pike/source/entity_manager.js", ['pike.core.EntityManager'], ['pike.graphics.Rectangle', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventHandler', 'goog.array']);
goog.addDependency("../../../Pike/source/events.js", ['pike.events.ChangePosition', 'pike.events.ChangeSize', 'pike.events.Update', 'pike.events.Render', 'pike.events.NewEntity', 'pike.events.RemoveEntity'], ['goog.events.Event', 'goog.events.EventTarget']);
